### ISSUE TITLE
能否首先查询数据库中是否有改文献

### ISSUE THREAD

**Issue by ChinJCheung** [MuiseDestiny/zotero-reference#10]
很多时候看某个主题的文献，有很多参考文献之前已经看过；再点击添加之后是否可以先搜寻数据库是否具有改文献，如果有检索到，提示用户，让用户选择是否直接关联这篇文献，而不是重复下载了一个新的条目。谢谢。

**Comment by MuiseDestiny** [comment]
本插件第一个版本就是优先搜索本地是否有该条目，然后从本地关联的。英文搜DOI，中文搜的标题。但是极端情况下，两篇中文文献同名可能就会出错。
