### ISSUE TITLE
参考文献不在连续的多个页面上，只会提取最后一个页面的参考文献

### ISSUE THREAD

**Issue by eloasankey** [MuiseDestiny/zotero-reference#100]
在某些文章中，参考文献不在连续的页面上，解析的参考文献只包含最后一个页面的参考文献，前面的参考文献无法解析出来，如第一张图是最后一个页面包含七个参考文献，但在它前一页还有30片参考文献没有解析出来。
文献doi：10.1038/s41563-020-00864-6

解析出来的参考文献：
![image](https://user-images.githubusercontent.com/18266597/227220500-87b2e2b4-1d5d-4456-96ae-5680da3fbd4c.png)
另一页上的其他参考文献：
![image](https://user-images.githubusercontent.com/18266597/227220725-dfd42016-7c60-4b7a-bd22-48d13c04258a.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/227456826-3ce25810-224e-40c7-91b5-6ef0820be1ea.png)
