### ISSUE TITLE
匹配本地条目无法显示

### ISSUE THREAD

**Issue by hflyellow** [MuiseDestiny/zotero-reference#102]
开发者你好：
更新最新版本的reference后，不在本地库中的文献无法以低透明度形式出现，所有文献均为一个颜色。而在昨天以前这个功能还可以正常使用。
![Snipaste_2023-03-24_10-20-16](https://user-images.githubusercontent.com/125798064/227407821-545e35cc-0aa0-4c77-9ffc-d902de77c25b.png)

**Comment by MuiseDestiny** [comment]
首选项设置最后一个0.5

**Comment by MuiseDestiny** [comment]
因为有人觉得这样会卡，我默认给关闭了

**Comment by hflyellow** [comment]
好的，非常感谢！！
