### ISSUE TITLE
建议能够更改参考文献的显示格式

### ISSUE THREAD

**Issue by dnvtmf** [MuiseDestiny/zotero-reference#104]
感谢作者的工作！

如果要知道文献的引用编号对应的文献，可以看侧边栏对应的条目，但是条目是“作者+标题+其他”的显示形式，不能一眼知道对应哪篇文献，需要把鼠标放上去才能看到标题。

![image](https://user-images.githubusercontent.com/10009911/227467183-88fa0aa8-f81a-4400-aa01-abd6b0c2abc0.png)

建议能够支持改变条目的显示格式，如标题在前，或作者缩写。

供参考，谢谢！

**Comment by MuiseDestiny** [comment]
浮窗是这个作用的。

你所说的各种形式，对于一篇文献，明确知道哪个是作者，哪个是标题，可以这么做。

但从pdf解析的结果，一团乱麻，暂时无法准确区分作者和标题以及期刊。所以是不可能支持自定义显示的。

**Comment by MuiseDestiny** [comment]
需要明确，插件得到的条目不是Zotero内部的条目，他只是一段文字。不支持丰富的格式调整。

**Comment by dnvtmf** [comment]
对于api的结果，应该比较准确

**Comment by dnvtmf** [comment]
或者只针对已在文献库中的参考文献

**Comment by MuiseDestiny** [comment]
> 或者只针对已在文献库中的参考文献

这样很难看的，在浮窗看很直观了。而且这个小功能工作量不小的。
