### ISSUE TITLE
是否可以优化某一参考文献涉及多篇文献的情况？

### ISSUE THREAD

**Issue by Finn9** [MuiseDestiny/zotero-reference#11]
如果某条参考文献涉及多篇文献，解析出来就会导致出现多个条目，文中参考文献的数字与右侧显示出来的数字不一致。
![image](https://user-images.githubusercontent.com/45392407/208304347-5d081485-b5b8-482f-92ac-084312dc9aca.png)

**Comment by MuiseDestiny** [comment]
欢迎来[米奇不妙屋](https://github.com/MuiseDestiny/zotero-reference/issues/6)反馈DOI或者文献地址
