### ISSUE TITLE
右边栏显示多个“参考文献”

### ISSUE THREAD

**Issue by Tobeprmn** [MuiseDestiny/zotero-reference#119]
你好，当我打开某篇PDF时，右边栏会显示多个“参考文献”按钮，见下图
![image](https://user-images.githubusercontent.com/119318291/230008811-df6e6638-00a2-4a53-bff2-5688407cf142.png)

**Comment by MuiseDestiny** [comment]
night插件导致，请禁用后试试

**Comment by Tobeprmn** [comment]
你好，禁用night插件后，仍然是这样，有些右边栏显示多个“参考文献”按钮，而有些又没有显示“参考文献按钮”，见下图：
![image](https://user-images.githubusercontent.com/119318291/230328259-fe885ee0-a89a-462b-9488-e4e222425f31.png)
![image](https://user-images.githubusercontent.com/119318291/230328305-60dc74ba-7fe4-4388-8a8b-45b3c6fb174c.png)

**Comment by MuiseDestiny** [comment]
关闭pdf重新打开呢

**Comment by Tobeprmn** [comment]
需要关闭所有已经打开的PDF才能恢复正常，但是重新打开后，每打开一篇PDF，右边栏就会多一个“参考文献”按钮，打开3篇PDF就会有3个“参考文献”按钮

**Comment by Tobeprmn** [comment]
我打开3篇PDF就这样子了
![230328259-fe885ee0-a89a-462b-9488-e4e222425f31](https://user-images.githubusercontent.com/119318291/230330790-f8aaaa8e-f255-4dfd-a76d-3171a6f28dd9.png)

**Comment by coisini-95** [comment]
我也会这样，打开两篇文献，后一篇打开的参考文献就会在前一篇那里显示，就会出现两个参考文献栏
![图片](https://user-images.githubusercontent.com/78250635/230530565-463416d9-3868-4a8d-aacd-dfb0d22bab35.png)

**Comment by MuiseDestiny** [comment]
> 我也会这样，打开两篇文献，后一篇打开的参考文献就会在前一篇那里显示，就会出现两个参考文献栏 ![图片](https://user-images.githubusercontent.com/78250635/230530565-463416d9-3868-4a8d-aacd-dfb0d22bab35.png)

night插件引起的。

**Comment by coisini-95** [comment]
> > 我也会这样，打开两篇文献，后一篇打开的参考文献就会在前一篇那里显示，就会出现两个参考文献栏 ![图片](https://user-images.githubusercontent.com/78250635/230530565-463416d9-3868-4a8d-aacd-dfb0d22bab35.png)
> 
> night插件引起的。

![图片](https://user-images.githubusercontent.com/78250635/230531352-95bc45bf-d1b8-4db1-aaae-4c3df64b4e64.png)
我没装night插件呀，跟主题相关的只有一个theme插件

**Comment by MuiseDestiny** [comment]
> 我没装night插件呀，跟主题相关的只有一个theme插件

我弄完style再修复哈

**Comment by coisini-95** [comment]
> > 我没装night插件呀，跟主题相关的只有一个theme插件
> 
> 我弄完style再修复哈

大佬辛苦了，不急，不是啥大问题

**Comment by coisini-95** [comment]
> > 我没装night插件呀，跟主题相关的只有一个theme插件
> 
> 我弄完style再修复哈

我发现了，就是theme插件的关系，把它关了就不会出现多个参考文献栏或者翻译栏了，我去那边反馈一下
![图片](https://user-images.githubusercontent.com/78250635/230714558-55dfb6f9-cc4c-4de3-aa42-d03441bdacfb.png)

**Comment by MuiseDestiny** [comment]
> > > 我没装night插件呀，跟主题相关的只有一个theme插件
> > 
> > 
> > 我弄完style再修复哈
> 
> 我发现了，就是theme插件的关系，把它关了就不会出现多个参考文献栏或者翻译栏了，我去那边反馈一下 ![图片](https://user-images.githubusercontent.com/78250635/230714558-55dfb6f9-cc4c-4de3-aa42-d03441bdacfb.png)

一般涉及修改pdf颜色的都会有影响

**Comment by jiuzhou1004** [comment]
> > > 我没装night插件呀，跟主题相关的只有一个theme插件
> > 
> > 
> > 我弄完style再修复哈
> 
> 我发现了，就是theme插件的关系，把它关了就不会出现多个参考文献栏或者翻译栏了，我去那边反馈一下 ![图片](https://user-images.githubusercontent.com/78250635/230714558-55dfb6f9-cc4c-4de3-aa42-d03441bdacfb.png)

十分感谢，找了一周终于找到可以暂时解决问题的方法了

**Comment by Gyllenhaalkk** [comment]
确实关闭了PDF背景色的插件就没有这个问题了，但长时间看文献确实得需要个护眼色，期待大佬能解决这个冲突！

**Comment by MuiseDestiny** [comment]
> 确实关闭了PDF背景色的插件就没有这个问题了，但长时间看文献确实得需要个护眼色，期待大佬能解决这个冲突！

能给出插件全名吗

**Comment by coisini-95** [comment]
> > 确实关闭了PDF背景色的插件就没有这个问题了，但长时间看文献确实得需要个护眼色，期待大佬能解决这个冲突！
> 
> 能给出插件全名吗

就是zotero theme

**Comment by MuiseDestiny** [comment]
> > > 确实关闭了PDF背景色的插件就没有这个问题了，但长时间看文献确实得需要个护眼色，期待大佬能解决这个冲突！
> > 
> > 
> > 能给出插件全名吗
> 
> 就是zotero theme

好的，目前是知道病根的，只是还不知道怎么解决

**Comment by Gyllenhaalkk** [comment]
> > > > 确实关闭了PDF背景色的插件就没有这个问题了，但长时间看文献确实得需要个护眼色，期待大佬能解决这个冲突！
> > > 
> > > 
> > > 能给出插件全名吗
> > 
> > 
> > 就是佐特罗主题
> 
> 好的，目前是知道病根的，只是还不知道怎么解决

![image](https://user-images.githubusercontent.com/102593651/231248358-dda3a163-49f2-492a-8070-31b9af12eb5e.png)
https://github.com/q77190858/zotero-pdf-background

**Comment by llity** [comment]
> > 我没装night插件呀，跟主题相关的只有一个theme插件
> 
> 我弄完style再修复哈

可以考虑增加主题功能吗？

**Comment by MuiseDestiny** [comment]
更新修复
