### ISSUE TITLE
按钮异常

### ISSUE THREAD

**Issue by Mashmall** [MuiseDestiny/zotero-reference#12]
打开右边工具栏之后图标消失

<img width="310" alt="Screenshot_4" src="https://user-images.githubusercontent.com/18736084/208367030-191ae80a-ddb8-4e91-b65e-14ab98a7da2e.png">

**Comment by MuiseDestiny** [comment]
一直是这种情况还是偶尔

**Comment by Mashmall** [comment]
> 一直是这种情况还是偶尔

刚刚测试卸载插件 还是无法显示 可能是软件或者其他软件冲突 谢谢
