### ISSUE TITLE
请问如何重新加载pdf中的参考文献数据

### ISSUE THREAD

**Issue by medecine-max** [MuiseDestiny/zotero-reference#122]
学位论文只有后两页的参考文献可以识别出来，可能是之前预读的页数调整少了，并且开了储存pdf源参考文献，现在刷新参考文献都显示[local]pdf,想请问下，如何删除之前储存的pdf源参考文献数据，谢谢~

**Comment by MuiseDestiny** [comment]
长按刷新即可

**Comment by medecine-max** [comment]
谢谢大佬~
