### ISSUE TITLE
请问现在支持鼠标悬浮论文内引用标号出悬浮框吗？

### ISSUE THREAD

**Issue by aeft** [MuiseDestiny/zotero-reference#123]
<img width="599" alt="zotero_rvDNmfiddX" src="https://user-images.githubusercontent.com/21154878/230751729-f4227f89-e86e-4892-af14-c979bf4de816.png">

如上图，是否支持鼠标悬浮然后出悬浮框呢？

现在是悬浮在右边的 References 才会出。

**Comment by MuiseDestiny** [comment]
这个功能不太好做，应该极少部分pdf支持这种悬浮

**Comment by aeft** [comment]
请问你说的“pdf支持”指的是pdf本身在引用标号处挂载了链接吗？即使没有链接，有一个比较trick的办法，就是比方说我框选 "[30]"，然后走右边的搜索接口，然后悬浮第一项。

**Comment by MuiseDestiny** [comment]
> pdf本身在引用标号处挂载了链接吗

pdf本身[1]是一个超链接，有可能会有浮窗弹出。

> 有一个比较trick的办法，就是比方说我框选 "[30]"，然后走右边的搜索接口，然后悬浮第一项。

以前这么做的容易误触，而且[29-31]就需要特别适配，readpaper做的很好。但是这个功能要对全pdf进行扫描，需要高时间付出，而且这个功能也不是什么特别大的功能，不值得。

**Comment by aeft** [comment]
请问以前这块代码是在哪个commit呢，我有空来改改。。关于误触这个，可以配合快捷键，或者只单独识别 "[30]" 这种单个引用的情况。

这个功能还挺重要的吧，我经常需要看引用的具体内容（标题和摘要）了解上下文。google 搜 “zotero jump reference and back” zotero 论坛上也有一些人问，一直没解决。

**Comment by MuiseDestiny** [comment]
> 请问以前这块代码是在哪个commit呢，我有空来改改。。关于误触这个，可以配合快捷键，或者只单独识别 "[30]" 这种单个引用的情况。
> 
> 这个功能还挺重要的吧，我经常需要看引用的具体内容（标题和摘要）了解上下文。google 搜 “zotero jump reference and back” zotero 论坛上也有一些人问，一直没解决。

但是有的不是这种序号，比如作者年份，很难适配所有，而且根据作者年份可能无法唯一确定是哪片参考文献。这方面readpaper也经常出错。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.3.7

**Comment by aeft** [comment]
明白了，谢谢。
