### ISSUE TITLE
pdf页面，tab 栏出现很多重复的tab

### ISSUE THREAD

**Issue by llity** [MuiseDestiny/zotero-reference#128]
偶尔出现重复的tab，有时候tab缺失。
<img width="604" alt="image" src="https://user-images.githubusercontent.com/11771112/231504391-0ec58c9a-cd6f-44fd-b5a6-5df5274b6aef.png">

**Comment by MuiseDestiny** [comment]
看看别的类似issue

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-reference/issues/119
