### ISSUE TITLE
zotero 信息栏中出现多个zotero-reference界面

### ISSUE THREAD

**Issue by AlexLee1992** [MuiseDestiny/zotero-reference#133]
你好，我的 zotero 信息界面中使用参考文献插件时经常显示如下图中多个参考文献界面，请问下这种应该怎么处理？
<img width="371" alt="image" src="https://user-images.githubusercontent.com/38725845/233257213-ba21d41b-3cda-46b0-bdab-4a715f7adc32.png">

**Comment by MuiseDestiny** [comment]
关闭主题相关插件
