### ISSUE TITLE
分割窗口后，新窗口PDF背景不起作用了。

### ISSUE THREAD

**Issue by llity** [MuiseDestiny/zotero-reference#142]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/11771112/236175824-8a957f0d-aa75-43ee-b5b5-aeeb132045fa.png">

这个拓展
https://github.com/q77190858/zotero-pdf-background

**Comment by MuiseDestiny** [comment]
> <img alt="image" width="236" src="https://user-images.githubusercontent.com/11771112/236175824-8a957f0d-aa75-43ee-b5b5-aeeb132045fa.png">
> 
> 这个拓展 https://github.com/q77190858/zotero-pdf-background

分割窗口是Zotero官方做的，与本插件无关，插件只是提供快捷入口。

**Comment by MuiseDestiny** [comment]
以我的了解，主题插件都对分割窗口无效，分割窗口也不可以做标注，翻译插件也会失效。
