### ISSUE TITLE
浮窗很容易消失

### ISSUE THREAD

**Issue by SalicylicAcid** [MuiseDestiny/zotero-reference#149]
鼠标稍微动快一点，或者碰到什么别的组件，浮窗就不能保持显示了。以下是视频演示。
![2](https://github.com/MuiseDestiny/zotero-reference/assets/37034452/5e2ba518-660b-427c-aaec-d262d8bf445e)

**Comment by MuiseDestiny** [comment]
首选项设置一下

**Comment by SalicylicAcid** [comment]
> 

试过了，不管用。不是时间问题。
