### ISSUE TITLE
浮窗消失过快的问题

### ISSUE THREAD

**Issue by cesaryuan** [MuiseDestiny/zotero-reference#154]
大佬好呀，最近发现了一个比较影响体验的问题，参考文献的浮窗消失太快，表现为：

当我将鼠标移动到浮窗上时，浮窗迅速消失（极少情况下不消失）

视频：

https://github.com/MuiseDestiny/zotero-reference/assets/35998162/753ecbe8-7345-44ad-b1f8-ad082396106a

视频中文献链接：[https://chn.oversea.cnki.net/kcms/detail/detail.aspx?filename=GCYZ202005006&dbcode=CJFD&dbname=CJFD2020&v=](https://chn.oversea.cnki.net/kcms/detail/detail.aspx?filename=GCYZ202005006&dbcode=CJFD&dbname=CJFD2020&v=)
版本：0.5.8
Zotero：6.0.26

**Comment by MuiseDestiny** [comment]
首选项可以设置这些时间的哦。

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-reference/assets/51939531/b36ad430-603a-4044-b934-d58f70d42337)

**Comment by cesaryuan** [comment]
> 首选项可以设置这些时间的哦。

嗯呐，我以为是这样的效果：

1. 鼠标离开参考文献条目后，若鼠标移动到浮窗上，则浮窗不消失；
2. 若鼠标移动到其他地方，浮窗经过500ms后自动消失。

现在也确实会在某些情景下实现第1条效果，但我不知道怎么稳定复现，比如下面视频里的[16]条目就可以达到1的效果：

https://github.com/MuiseDestiny/zotero-reference/assets/35998162/8158b4ca-83cb-48de-b715-f0bfedf6f7e8

但是当我把条目换成[15]后，效果1就无法复现了


https://github.com/MuiseDestiny/zotero-reference/assets/35998162/92d136b5-fb62-4f5d-9819-de2814285df1

**Comment by MuiseDestiny** [comment]
注意下，你在【15】移动到浮窗的时候经过了【16】，此时会触发【16】的浮窗，【16】会把当前界面所有浮窗清空后再显示【16】。

总之：经过了【16】，注意鼠标横向移动到浮窗，不要划过其它的，会伤及无辜。

**Comment by MuiseDestiny** [comment]
其实这也是浮窗为什么这么设计显示的原因。一个横向移动可以确保不经过其它参考文献进入浮窗。

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-reference/assets/51939531/385b49a7-9e19-4bdf-8fce-f1f3635f1441)

也因为这个，堆叠视图的浮窗不好做。

**Comment by cesaryuan** [comment]
明白啦！

不过感觉对鼠标移动要求很高的样子哈哈，因为那个参考文献条目还挺细的，要实现不碰到其他条目而横向移动到浮窗有点小难度😂

不过算是知道原因所在啦，谢谢大佬

**Comment by MuiseDestiny** [comment]
> 

所以有人建议做成点击显示浮窗，不消失，但感觉没有这种丝滑。
