### ISSUE TITLE
识别双栏pdf参考文献效果不太好

### ISSUE THREAD

**Issue by B1INGO** [MuiseDestiny/zotero-reference#156]
**不礼貌不回复，直接关闭**

PDF解析失败，汇报到<https://github.com/MuiseDestiny/zotero-reference/issues/6>。

请确保已安装最新版本插件。
已安装最新版本
pdf:https://link.springer.com/article/10.1007/s41095-022-0271-y
详细描述：
源文档有100多个文献。但是识别出来只有20个参考文献。
![截屏2023-06-03 22 47 57](https://github.com/MuiseDestiny/zotero-reference/assets/20365172/5c1c8946-8a28-482b-9aec-2751bf0179b9)

**Comment by MuiseDestiny** [comment]
汇报到#6
