### ISSUE TITLE
导出文章提取出的references

### ISSUE THREAD

**Issue by ArmandXiao** [MuiseDestiny/zotero-reference#158]
首先，十分感谢您做出的好插件。

请问有没有一种方法，可以把文章中识别出的所有reference导出到 csv，或者 txt。
目的是：收集文章所有的references。

或者，有没有可以调用的api，能从pdf中提取所有的references。
类似的repo有：https://github.com/metachris/pdfx
但是这个repo的效果，不及此插件识别的准确率。

期待您的回复，谢谢 😃

**Comment by MuiseDestiny** [comment]
双击xx条参考文献这里，可以导出到剪贴板，然后进一步处理。
![image](https://github.com/MuiseDestiny/zotero-reference/assets/51939531/2c875117-4c19-4f9f-b4f2-37b9ff690526)

**Comment by MuiseDestiny** [comment]
英文参考
https://github.com/MuiseDestiny/zotero-reference/blob/bootstrap/src/modules/api.ts
搜索crossref，有现成的api

**Comment by ArmandXiao** [comment]
> 双击xx条参考文献这里，可以导出到剪贴板，然后进一步处理。 ![image](https://user-images.githubusercontent.com/51939531/244080108-2c875117-4c19-4f9f-b4f2-37b9ff690526.png)

多谢您的回复。

这个方法适用于某一篇文。
如果我有几百篇文章，目前有方法可以批量导出吗？
