### ISSUE TITLE
不知能否自动识别文库中已经有的文献

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-reference#16]
目前好像在保存参考文献时，不会识别该参考文献是否在我的文库中已经存在

**Comment by MuiseDestiny** [comment]
> 目前好像在保存参考文献时，不会识别该参考文献是否在我的文库中已经存在

会识别的，如果是有DOI，会进行搜索
![image](https://user-images.githubusercontent.com/51939531/208808175-d3f4de4d-0e83-4b5e-aefb-4aa6b707bfa8.png)
如果关联存在，初始化时侯，会呈现`-`而不是`+`。

添加关联时，中文会搜索标题，英文DOI，如果本地存在文献会与本地文献关联，没有的才会新建一个条目。
![image](https://user-images.githubusercontent.com/51939531/208808294-157e05ef-c5b1-4d89-8027-27cc0497e9e0.png)
![image](https://user-images.githubusercontent.com/51939531/208808358-b5ad4a65-780f-46d2-81d0-f89615313e27.png)

**Comment by 17816712353** [comment]
我刚刚试了一下，好像没有😂。。。
![image](https://user-images.githubusercontent.com/68216639/208872900-9204f573-bc9e-400a-98b4-629df233b24e.png)
![image](https://user-images.githubusercontent.com/68216639/208873033-f7b0fe58-7071-47f2-9ad9-62e29f029c52.png)

**Comment by 17816712353** [comment]
作者和插件已经超级牛了，再稍稍提个建议，如果能打开一后，保存参考文献的相关信息，不用每次打开PDF都要识别一次就更佳了！

**Comment by MuiseDestiny** [comment]
> 作者和插件已经超级牛了，再稍稍提个建议，如果能打开一后，保存参考文献的相关信息，不用每次打开PDF都要识别一次就更佳了！

因为现在还不稳定，可能识别错误。等稳定了可以这么做，节省时间。

**Comment by wangfh5** [comment]
我也是发现有些明明DOI对得上的本地文献条目, 却无法在reference中检索到...

这是文献库里面的文献词条, 是有DOI的
![image](https://user-images.githubusercontent.com/51868839/228837396-fc1ffe83-9ef0-4a91-bf40-9d78b8207855.png)
这是reference生成的参考文献列表, 对应的[26]明明与上面的本地文献词条DOI一模一样, 却无法与之关联
![image](https://user-images.githubusercontent.com/51868839/228837594-74434f1d-4076-4529-9ff6-ff4174a40f15.png)

另外还有一个问题是, PDF源和API源的参考文献对本地文献库中的搜索关联结果竟然不一样. 如下图所示, 分别是PDF源和API源的reference列表, 前者能搜索上的文献, 后者却没认出来, 
![image](https://user-images.githubusercontent.com/51868839/228838319-ded4120f-10cd-4808-b579-f87c48a42645.png)
![image](https://user-images.githubusercontent.com/51868839/228838346-0df68380-ca71-41ba-a896-f99d637595e9.png)

**Comment by MuiseDestiny** [comment]
本地DOI是啥，然后ref查找到的是什么。

> 我也是发现有些明明DOI对得上的本地文献条目, 却无法在reference中检索到...

**Comment by wangfh5** [comment]
> 本地DOI是啥，然后ref查找到的是什么。
> 
> > 我也是发现有些明明DOI对得上的本地文献条目, 却无法在reference中检索到...

我刚刚更新了上面那条回复

**Comment by MuiseDestiny** [comment]
> > 本地DOI是啥，然后ref查找到的是什么。
> > > 我也是发现有些明明DOI对得上的本地文献条目, 却无法在reference中检索到...
> 
> 我刚刚更新了上面那条回复

长按refresh刷新呢。

**Comment by MuiseDestiny** [comment]
奇怪了，发一下整个pdf我看看

**Comment by wangfh5** [comment]
> 

长按刷新没有任何改变, 相关的PDF如下. 
[Wang et al. - 2019 - Synthesis of antisymmetric spin exchange interacti.pdf](https://github.com/MuiseDestiny/zotero-reference/files/11117231/Wang.et.al.-.2019.-.Synthesis.of.antisymmetric.spin.exchange.interacti.pdf)

**Comment by MuiseDestiny** [comment]
> > 
> 
> 长按刷新没有任何改变, 相关的PDF如下. [Wang et al. - 2019 - Synthesis of antisymmetric spin exchange interacti.pdf](https://github.com/MuiseDestiny/zotero-reference/files/11117231/Wang.et.al.-.2019.-.Synthesis.of.antisymmetric.spin.exchange.interacti.pdf)

![image](https://user-images.githubusercontent.com/51939531/229000612-75cfdd4b-189a-42ab-a746-b3c6fb89ac3c.png)

你这个PDF解析出来是没有DOI的，浮窗里的DOI是搜索出来的。根据标题搜索出来的DOI（不是百分百准确）不参与本地查找。

那种PDF有超链接，或者明确给出doi的参考文献，才能搜索本地doi匹配。

**Comment by wangfh5** [comment]
但为什么有些本地文献，PDF源这个靠标题搜索的能搜到，但是api源反而搜索不到了？我前面修改的回复里面有两种情况的截图

**Comment by MuiseDestiny** [comment]
> 但为什么有些本地文献，PDF源这个靠标题搜索的能搜到，但是api源反而搜索不到了？我前面修改的回复里面有两种情况的截图

api源返回的doi偶尔会有标题
