### ISSUE TITLE
Zotero7 Beta版 不显示设置界面

### ISSUE THREAD

**Issue by Theigrams** [MuiseDestiny/zotero-reference#161]
**不礼貌不回复，直接关闭**

您好，首先感谢您的插件，真的很好用。
我目前的环境是 m1 Mac，Zotero7 Beta版，插件的版本是最新的预览版 https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.5.9

刚安装后插件能正常使用，但我后来又用Zotero6打开同一个profile，可能是这个原因导致数据库冲突了。
最后我再打开Zotero7 Beta时，发现设置功能没法显示了，把插件卸载重装依然无法正常显示。
不过幸好目前还可以通过Advanced Preferences进行设置。

请问在卸载重装都失效的情况下，该怎么处理呢？

<img width="912" alt="image" src="https://github.com/MuiseDestiny/zotero-reference/assets/26341831/48c61d47-4214-454f-a420-334a67d0d3e2">

<img width="1112" alt="image" src="https://github.com/MuiseDestiny/zotero-reference/assets/26341831/f9a7b23d-24bc-4aa0-abb9-47b98c95b361">

**Comment by MuiseDestiny** [comment]
稍等一段时间因为zi7最近有改动，导致大部分插件首选项设置都不显示。可以通过config临时修改设置。后面会适配修复。

**Comment by MuiseDestiny** [comment]
是因为zo7有一个小更新导致的。不用尝试重装，等待插件更新。

**Comment by Theigrams** [comment]
好的，非常感谢
