### ISSUE TITLE
zotero7 beta14 ，reference和style插件设置界面空白

### ISSUE THREAD

**Issue by jlu511** [MuiseDestiny/zotero-reference#164]
**不礼貌不回复，直接关闭**

PDF解析失败，汇报到<https://github.com/MuiseDestiny/zotero-reference/issues/6>。

请确保已安装最新版本插件。reference和style插件都是最新版面向zotero 7 更新的。0.5.9

请附带PDF或者URL或者DOI或者arXivID，开发者不会魔法，单放一张截图，一段文字描述bug不会修复。总之越详细越好，太简洁的issue不会得到回复。
![image](https://github.com/MuiseDestiny/zotero-reference/assets/64378673/f552bb00-a927-48f5-b7e6-4897146389e4)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-reference/releases/download/0.5.9/zotero-reference-v2.xpi
