### ISSUE TITLE
“刷新”按钮多次点击，结果不一且错序。

### ISSUE THREAD

**Issue by onefanwu** [MuiseDestiny/zotero-reference#17]
您好！
非常感谢您向公众提供如此便利的插件。这里我也给出一些使用过程中的bugs，我发现点击刷新按钮显示的结果会不一样，不仅如此识别出的参考文献序号与真实序号相比是严重错序的。如下图所示：
所识别的文献是：Foedus: Oltp engine for a thousand cores and NVRAM
第一次点击显示23条参考文献，但真实是有37条。
![image](https://user-images.githubusercontent.com/96245396/208811383-bdca02bb-7853-462c-bbab-adecdc18a9b1.png)

第二次点击显示36条参考文献。
![image](https://user-images.githubusercontent.com/96245396/208811564-0d2558af-1c7f-4927-8944-30cc6424bd16.png)

**Comment by MuiseDestiny** [comment]
感谢你的反馈。
由于插件支持PDF解析和API获取两种方式。

首次打开PDF会解析PDF，点击刷新调用API，再次点击刷新又重新PDF解析，再刷新又是API...

第一次的23显然是PDF解析失败，第二次的36是API的返回结果，我试了下，确实少了一条[31]
![image](https://user-images.githubusercontent.com/51939531/208816575-13bc1922-2022-4726-a634-226cd9d035ce.png)

我优化了PDF识别，que'shi确实是37条。
![image](https://user-images.githubusercontent.com/51939531/208817800-614dc8bb-0aab-4867-b037-449270814940.png)

还有PDF解析失败欢迎https://github.com/MuiseDestiny/zotero-reference/issues/6

**Comment by onefanwu** [comment]
哇塞，感谢反馈，楼主真是敬业哈哈！
另：#6的名字——“米奇不妙屋”，让人看不出来是bug反馈楼哈哈

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/208818631-a5a70b4a-018e-4d9e-a315-8bd9c801ee72.png)
有意思的是readpaper识别也少了一个，可能是也调用api了。

**Comment by onefanwu** [comment]
@MuiseDestiny 哈哈，那估计也是。lz要是做成和readpaper那样，触碰引用符号就能弹出参考文献信息那样的就很超棒了。
作为用户，最希望的就是在看文献的时候对照着引用序号快速知道是哪篇文献，因为总是翻到pdf末尾找很麻烦，其余倒是细节。
加油lz！！！
