### ISSUE TITLE
在部分 pdf 中鼠标放在交叉引用的公式上会显示不相关的参考文献

### ISSUE THREAD

**Issue by syvshc** [MuiseDestiny/zotero-reference#172]
**不礼貌不回复，直接关闭**

PDF解析失败，汇报到<https://github.com/MuiseDestiny/zotero-reference/issues/6>。

请确保已安装最新版本插件。

请附带PDF或者URL或者DOI或者arXivID，开发者不会魔法，单放一张截图，一段文字描述bug不会修复。总之越详细越好，太简洁的issue不会得到回复。

只激活了 zotero-reference 插件, 使用的文章为 http://arxiv.org/abs/2210.11960 , 刷新参考文献后把鼠标放在公式的引用 (x.y) 上的时候, 会显示参考文献, 不知道是什么情况, 麻烦作者了
![image](https://github.com/MuiseDestiny/zotero-reference/assets/38098591/7c598718-5f8a-430f-96a9-abdbf84887f3)

**Comment by MuiseDestiny** [comment]
这是已知Bug，初衷是：如果是[1]，放到上面，会显示1对应的文献。

**Comment by syvshc** [comment]
> 这是已知Bug，初衷是：如果是[1]，放到上面，会显示1对应的文献。

能感觉出来是想做这个事, 那我先把这个功能关掉了, 谢谢作者大大
