### ISSUE TITLE
学术论文参考文件刷的问题

### ISSUE THREAD

**Issue by llyzot** [MuiseDestiny/zotero-reference#173]
1. 知网是局域网自动登录的，这个是无法配置的，刷新时提示配置知网研学账后后重试，然后提示400：null，请问这个该如何处理

![image](https://github.com/MuiseDestiny/zotero-reference/assets/26666662/e948ffe7-0384-475f-9c6c-cd47e56d5090)

![image](https://github.com/MuiseDestiny/zotero-reference/assets/26666662/5c3ee498-0a8d-4c21-884d-ed9bd30221d1)

2. 有时候刷新时能成功的，但是只能刷处来少数的几篇，从提示来看这个应该是从PDF内读取的
![image](https://github.com/MuiseDestiny/zotero-reference/assets/26666662/7554cc64-64b8-4f5f-952b-84dd4d00153c)

![image](https://github.com/MuiseDestiny/zotero-reference/assets/26666662/ac5e2c91-8955-4620-b3cb-51e00d97403b)

**Comment by llyzot** [comment]
![image](https://github.com/MuiseDestiny/zotero-reference/assets/26666662/6cf6e2c1-b2ce-414b-8e3c-d6d51962c9d0)
配置成优先从pdf中获取后，并将预读取页面最后的页数增加后，可获取到学位论文的全部参考文献

**Comment by MuiseDestiny** [comment]
> 这个是无法配置的

你注册个账号配置上就行了

**Comment by llyzot** [comment]
大佬，自己注册的没有知网的下载权限诶，知网是局域网自动登录的茉莉花是可以使用的

**Comment by MuiseDestiny** [comment]
> 大佬，自己注册的没有知网的下载权限诶，知网是局域网自动登录的茉莉花是可以使用的

这里是用于获取参考文献，不需要有下载权限的

**Comment by llyzot** [comment]
就是说必须要需要独立的账号才能获取知网的参考文献？

**Comment by MuiseDestiny** [comment]
> 就是说必须要需要独立的账号才能获取知网的参考文献？

按照要求配置即可。**知网研学**是cnki的产品

**Comment by llyzot** [comment]
多谢大佬，查看往期配置了个人的知网账户，可以从API获取参考文献了
[0.3.8: 完美支持知网API，需要配置知网研学账号密码](https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.3.8)
