### ISSUE TITLE
存在部分参考文献的浮窗无法停留，导致无法复制浮窗内的文字

### ISSUE THREAD

**Issue by MilkGe** [MuiseDestiny/zotero-reference#174]
鼠标停留在参考文献上，这将显示浮窗，这一步正常。但当我将鼠标进一步移动到显示出来的浮窗复制内容时，浮窗消失（如下GIF图）。值得注意的是有的参考文献并不会出现该问题。总之，部分参考文献会这样，也不知为何（我安装的是0.5.8的版本，pre-release的那几个v1,v2版本等暂不安装，因为在zotero6上右边栏不显示“参考文献”这个功能选项。更新到zotero7可解决不显示的问题，但会导致我其他部分插件无法兼容，因此我选择zotero reference 0.5.8版本）
![issue1](https://github.com/MuiseDestiny/zotero-reference/assets/131436945/caf72f4d-00f5-4ba9-be2d-a6fb9363d437)
)

**Comment by MuiseDestiny** [comment]
水平横向移动，请不要再经过其它条目

**Comment by MilkGe** [comment]
好的 @MuiseDestiny ，已解决
