### ISSUE TITLE
Zotero7无法获取参考文献

### ISSUE THREAD

**Issue by wang1882** [MuiseDestiny/zotero-reference#178]
大佬好，刚才更新Zotero7 beta.29后插件无法获取参考文献了，点击“刷新”没有任何反应。
![image](https://github.com/MuiseDestiny/zotero-reference/assets/140906369/b2bb039f-4776-4f41-a24c-3bbc5cba4a9f)

卸载重新安装插件也不行。

**Comment by MuiseDestiny** [comment]
等更新

**Comment by MuiseDestiny** [comment]
这次大更新，需要插件去适配它

**Comment by MedAIerHHL** [comment]
> 这次大更新，需要插件去适配它
您好，想请问下，插件现在适配了zotero7嘛，我安装上了但是显示是空白的
![image](https://github.com/MuiseDestiny/zotero-reference/assets/102724737/8d6e1fe3-017b-4bb1-b329-f204a46743c5)

**Comment by MuiseDestiny** [comment]
> > 这次大更新，需要插件去适配它
> > 您好，想请问下，插件现在适配了zotero7嘛，我安装上了但是显示是空白的
> > ![image](https://user-images.githubusercontent.com/102724737/261850978-8d6e1fe3-017b-4bb1-b329-f204a46743c5.png)

https://github.com/MuiseDestiny/zotero-reference/releases
