### ISSUE TITLE
频繁切换点击不同pdf文献，插件容易造成软件卡顿

### ISSUE THREAD

**Issue by onefanwu** [MuiseDestiny/zotero-reference#18]
您好！
    我在使用过程中有时候经常切换不同文献，但zotero-reference每次点击进入一个文献就进行识别references，对于已经识别过的参考文献依旧重复识别。当我短时间内切换进入4个文献pdf时就造成了软件卡顿。
    希望能够优化一下这个细节，不重复识别已经识别过的文献。或者给用户一个可选项就是暂停自动识别，而是让用户在有需要的时候手动点击“刷新”进行识别。

**Comment by MuiseDestiny** [comment]
好的
