### ISSUE TITLE
能否提供匹配pubmed源功能呢？

### ISSUE THREAD

**Issue by 1tonsilla** [MuiseDestiny/zotero-reference#183]
我是医疗系统的，目前参考文献都是通过doi识别，有时候要么搜不到，要么点开来是某出版社的网站（可能是）
目前医疗系统基本文献都是从pubmed上搜的，希望提供选项，通过文件名去pubmed上找文献的功能（搞医疗的，基本一个pubmed就通吃了），这样pubmed打开对于一些比如easyScholar等插件支持更好 
如下图：
![image](https://github.com/MuiseDestiny/zotero-reference/assets/33661246/bc3673f7-3ea9-4af4-87b9-96a224e63fc7)

谢谢！

**Comment by MuiseDestiny** [comment]
意思是做一个搜索引擎吗

**Comment by 1tonsilla** [comment]
> 意思是做一个搜索引擎吗

不是右上角那个搜索引擎~
用图说话吧，就是这个意思：
目前想具体看一篇参考文献，ctrl+左键 经常跳转的就是杂志社的官网（五花八门的），或者就是提示DOI未找到
![image](https://github.com/MuiseDestiny/zotero-reference/assets/33661246/a4576a14-e8dd-4e59-b849-df9e40694774)
![image](https://github.com/MuiseDestiny/zotero-reference/assets/33661246/889768fe-4ca1-4464-8d49-8ab107dad160)
![image](https://github.com/MuiseDestiny/zotero-reference/assets/33661246/4c31e884-34c9-43e0-b8c5-54ede203fa18)

我不知道别的行业怎么样，但是pubmed上搜医学文献，基本是最官方的了，所以我希望我的reference的所有文章都去pubmed上找源~
老哥应该懂我意思了吧 ^_^
希望reference的软件设置里，提供pubmed的文章源选择

**Comment by MuiseDestiny** [comment]
做不到的。doi跳到哪不可控

**Comment by 1tonsilla** [comment]
> 做不到的。doi跳到哪不可控

我以为可以直接ctrl+单击 自动复制文件名去pubmed上搜索呢..

**Comment by MuiseDestiny** [comment]
> > 做不到的。doi跳到哪不可控
> 
> 我以为可以直接ctrl+单击 自动复制文件名去pubmed上搜索呢..

doi就是一个中转，跳到文献的最终地址，也就是期刊所在。pubmed我理解是个搜索引擎吧，他不是最终地址。这种适配可以做。但是B用户说XX好用，再去适配XX，C用户说XXX好用，再去适配XXX，太繁琐了，这不是插件的工作。

**Comment by 1tonsilla** [comment]
> > > 做不到的。doi跳到哪不可控
> > 
> > 
> > 我以为可以直接ctrl+单击 自动复制文件名去pubmed上搜索呢..
> 
> doi就是一个中转，跳到文献的最终地址，也就是期刊所在。pubmed我理解是个搜索引擎吧，他不是最终地址。这种适配可以做。但是B用户说XX好用，再去适配XX，C用户说XXX好用，再去适配XXX，太繁琐了，这不是插件的工作。

好的，理解，对于医疗行业 基本清一色的pubmed，但是行业太多了，理解。我目前先用quicker的动作曲线救国吧~
