### ISSUE TITLE
Physics Review 系列和 The Astrophysical Journal 的文章 API 识别效果差

### ISSUE THREAD

**Issue by skq1998** [MuiseDestiny/zotero-reference#184]
## 插件表现

![image](https://github.com/MuiseDestiny/zotero-reference/assets/40002305/7c910e9b-073c-453a-9762-f8a4918cb19a)

通过 api 更新参考文献后，结果如图，不显示作者和文章标题。目前 Physical Review 系列和 The Astrophysical Journal 都出现了这个问题

## 测试过的文章

- 00年的 `PRA` DOI 为 10.1103/PhysRevA.62.022708
- 01年的 `Astrophys. J.` DOI 为 10.1086/321512
- 23年的 `PRL` DOI 为 10.1103/PhysRevLett.131.046501

图中结果是23年这篇 PRL 的结果

## 参照物

Nature 的文章（doi: 10.1038/s41586-021-04205-8）识别效果很好

![image](https://github.com/MuiseDestiny/zotero-reference/assets/40002305/52cd458b-3ad9-44df-b5ea-2c2c0ecfe726)

> 不清楚这个是 API 源的问题，还是插件识别的问题，请开发者核验

**Comment by MuiseDestiny** [comment]
数据源就是这样缺失，没办法

**Comment by MuiseDestiny** [comment]
不鼓励使用api，api一般都是残缺的

**Comment by skq1998** [comment]
好的，感谢
