### ISSUE TITLE
PDF解析失败反馈

### ISSUE THREAD

**Issue by Perran1013** [MuiseDestiny/zotero-reference#188]
### 参考文献不匹配

<div type='discussions-op-text'>

PDF解析混乱，可能由于其所属的《艺术评论》期刊的截断词为“注释”。随附参考
pdf上传至评论区（不知道为什么这里上传不成功T T）
DOI：10.16364/j.cnki.cn11-4907/j.2022.02.011

</div>
[《雄狮少年》：国产现实主义动画电影的新探索_邹波.pdf](https://github.com/MuiseDestiny/zotero-reference/files/12417553/_.pdf)
<img width="1609" alt="截屏2023-08-23 17 07 31" src="https://github.com/MuiseDestiny/zotero-reference/assets/142981468/c228d90f-26e7-436c-ae12-2edba9ea9954">

**Comment by Perran1013** [comment]
[《雄狮少年》：国产现实主义动画电影的新探索_邹波.pdf](https://github.com/MuiseDestiny/zotero-reference/files/12417537/_.pdf)

**Comment by MuiseDestiny** [comment]
即便截断词加上”注释“，你pdf中还有【】符号。解析失败请去https://github.com/MuiseDestiny/zotero-reference/discussions/81

**Comment by MuiseDestiny** [comment]
中文的即便解析出来，浮窗信息可能也不对，不建议在中文文献使用。
