### ISSUE TITLE
Quick Peek Color aware

### ISSUE THREAD

**Issue by sleepymalc** [MuiseDestiny/zotero-reference#194]
這個功能非常好用，但現在並不匹配當前pdf顏色，希望顏色能一樣：
<img width="570" alt="image" src="https://github.com/MuiseDestiny/zotero-reference/assets/60427058/a28617e1-e8bf-4ea5-b27f-ec7e492951c8">

**Comment by MuiseDestiny** [comment]
这是zotero自己提供的功能，与插件无关
