### ISSUE TITLE
侧边栏不出现参考文献按钮

### ISSUE THREAD

**Issue by sknin** [MuiseDestiny/zotero-reference#2]
Zotero版本6.0.18，安装zotero-reference0.0.4，侧边栏不出现参考文献按钮；将Sci-Hub Plugin for Zotero1.4.4插件disable了，还是不出现参考文献按钮

**Comment by LamFTS** [comment]
同样问题，出现在Linux版本，未安装Sci-hub插件。

**Comment by baijing-0656** [comment]
重启了zotero几次都没有出现，只在右下角提示抓取了多少篇参考文献，但是在使用中突然又有了。新打开的文献没有，但是点击已打开的能正常显示的文献之后，再点击新打开的文献也能在右边出现参考文献了。感觉这个问题和zotero-translate存在的问题有些像。

**Comment by Sifan798** [comment]
我的也是这样，安装插件之后不显示参考文献，就像没安装之前一样

**Comment by Sifan798** [comment]
我（zotero6.0.18，zotero-reference0.0.6）也是这样，安装插件之后不显示参考文献，没有任何迹象，就像没安装之前一样

**Comment by MuiseDestiny** [comment]
> 我（zotero6.0.18，zotero-reference0.0.6）也是这样，安装插件之后不显示参考文献，没有任何迹象，就像没安装之前一样

帮助，输出日志排错，查看输出文件，然后点开一篇文献，我看看输出

**Comment by Sifan798** [comment]
好的，ID是D608197419

**Comment by MuiseDestiny** [comment]
> 好的，ID是D608197419

我重新上传了一个0.0.6,上一个debug有点异常。麻烦重新安装截图一下我看看
![image](https://user-images.githubusercontent.com/51939531/208238541-a7a1d7ed-8305-4030-b1cc-bebcc7b5752d.png)
