### ISSUE TITLE
中文参考文献刷新后序号会重复

### ISSUE THREAD

**Issue by Serendipity-LJ** [MuiseDestiny/zotero-reference#20]
中文文献第一次打开PDF如果手贱点了两次刷新：重新加载两次参考文献后，参考文献前的序号 [ ] 会重复，不知如何删除重复的序号。参考文献条目没有重复，只有开头的序号重复了两次。

**Comment by MuiseDestiny** [comment]
> 中文文献第一次打开PDF如果手贱点了两次刷新：重新加载两次参考文献后，参考文献前的序号 [ ] 会重复，不知如何删除重复的序号。参考文献条目没有重复，只有开头的序号重复了两次。

应该是我把测试版错发出来了，在github重新下载安装试试。
