### ISSUE TITLE
首选项里面此插件的设置页面打不开

### ISSUE THREAD

**Issue by Aaronlves** [MuiseDestiny/zotero-reference#204]
![image](https://github.com/MuiseDestiny/zotero-reference/assets/37626504/b023c373-7ef7-4630-b187-4fb0066fad35)
不管怎么点都打不开，只能显示上一个点击进入的其他插件设置页面。我自下载就没有成功打开过，但是我看好像没人反应这个问题，至少我没找到。

把所有其他插件都禁用也不行。
![image](https://github.com/MuiseDestiny/zotero-reference/assets/37626504/48e10f6a-d747-4d56-b3b3-2c692360a8bb)

**Comment by Einstress** [comment]
同问，我也是这样的问题，m1 mac，zotero7

**Comment by lymyxhw** [comment]
同问，zotero(7.0.0-beta.44+64a78412c (64-bit))，插件版本0.6.3，disable其余插件也无法打开插件设置页面，pdf点链接也没有自动分屏，是不适配还是其他问题，谢谢

**Comment by shiyuzhang98** [comment]
> 同问，我也是这样的问题，m1 mac，zotero7

我也是这样

**Comment by annayao-14** [comment]
我也是这样

**Comment by MuiseDestiny** [comment]
没升级导致的

**Comment by annayao-14** [comment]
> 没升级导致的

是什么东西没升级啊？主语是什么呢？

**Comment by Aaronlves** [comment]
> 没升级导致的

你好，我刚刚检查了zotero和所有插件，全部都是最新版本。我不太懂您说的是什么地方没升级。但是除了不能够打开设置页面之外，其他功能可以正常使用！非常感谢你的贡献！

**Comment by lymyxhw** [comment]
> 没升级导致的

你好，win10 zotero-7.0.0-beta.46+c27bac2ad (64-bit)，插件0.6.4，重启过，目前打不开设置页面，图片链接还是直接跳转到图片所在页，没有自动分屏，好在reference还是读得出来，是目前还不兼容么？非常感谢你的贡献，谢谢！

**Comment by luxueqiang** [comment]
我也是同样的问题
