### ISSUE TITLE
悬浮窗呈现的内容不完整且无法调整大小

### ISSUE THREAD

**Issue by pengchonghao** [MuiseDestiny/zotero-reference#205]
![image](https://github.com/MuiseDestiny/zotero-reference/assets/50258553/c4073e84-2e19-415f-9d7c-13fa64e9401b)
如图所示，无论是参考文献的悬浮窗还是图片的悬浮窗，都无法通过鼠标滚轮（＋ctrl）调整大小，更不能复制

**Comment by MuiseDestiny** [comment]
这个功能与ref插件无关，是zotero自己功能额

**Comment by pengchonghao** [comment]
感谢告知！！很抱歉给您额外增添回复问题的工作量




彭重昊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MuiseDestiny/zotero-reference"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月5日(星期四) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MuiseDestiny/zotero-reference] 悬浮窗呈现的内容不完整且无法调整大小 (Issue #205)





 
这个功能与ref插件无关，是zotero自己功能额
