### ISSUE TITLE
浮窗建议

### ISSUE THREAD

**Issue by Mashmall** [MuiseDestiny/zotero-reference#21]

**Comment by Mashmall** [comment]
能否设置左键或者右键打开浮窗，点击其他地方关闭。现在默认的悬停经常鼠标拉过去浮窗信息就没了，我看现在左右键都是复制ref，有点冗余，谢谢您

**Comment by MuiseDestiny** [comment]
> 能否设置左键或者右键打开浮窗，点击其他地方关闭。现在默认的悬停经常鼠标拉过去浮窗信息就没了，我看现在左右键都是复制ref，有点冗余，谢谢您

![image](https://user-images.githubusercontent.com/51939531/209267466-6aab47be-9983-4786-9cac-ed9ca8c8d246.png)
可以把1000改成更大

**Comment by MuiseDestiny** [comment]
需要重新安装最新版

**Comment by Mashmall** [comment]
好的  还是希望有按键触发 只是建议 谢谢您

**Comment by MuiseDestiny** [comment]
> 好的 还是希望有按键触发 只是建议 谢谢您

好的，下个版本加
