### ISSUE TITLE
启用zotero-reference后，zotero设置界面异常

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-reference#22]
这是启用前
![image](https://user-images.githubusercontent.com/68216639/209328303-0374e637-c180-4563-aee7-250853077f4b.png)

这是启用后
![image](https://user-images.githubusercontent.com/68216639/209328157-e92daa70-4868-4945-bda7-5eb3ebe0ad50.png)

**Comment by MuiseDestiny** [comment]
哇哇，不好意思，我重新弄一下logo

**Comment by MuiseDestiny** [comment]
重新下载最新版安装试试，另外，请问你侧边栏可以正常显示嘛

**Comment by 17816712353** [comment]
> 重新下载最新版安装试试，另外，请问你侧边栏可以正常显示嘛

🐮。恢复正常了，然后侧边栏也可以正常显示的。
