### ISSUE TITLE
浮窗背景透明度显示问题

### ISSUE THREAD

**Issue by manipulative** [MuiseDestiny/zotero-reference#220]
您好，我在使用过程中，reference列表的浮窗背景是透明的，会和文章文字重叠，请问如何解决这一问题呢？
![image](https://github.com/MuiseDestiny/zotero-reference/assets/26652791/c99af8bb-15c4-4441-b264-8d40195126fd)

我的插件版本是0.6.3，zotero版本是7.0.0-beta.53+969031a37

谢谢您的耐心解答！

**Comment by larry8916** [comment]
我的也是如此

**Comment by larry8916** [comment]
1. Change the zotero language to Chinese(simple, 将Zotero软件语言设置为简体中文);
2. open the add-on preference(首选项)，找到“浮窗”；
3. 将“背景色”从‘undefined’改成其他不透明的html颜色代码，如“#e0e0d1‘’。见下：

![image](https://github.com/MuiseDestiny/zotero-reference/assets/24448319/a639ea79-467d-4958-b785-f63a46b0decd)
‘’

**Comment by luxueqiang** [comment]
mac版本无法进入设置菜单~

**Comment by larry8916** [comment]
> mac版本无法进入设置菜单~

Change the zotero language to Chinese(simple, 将Zotero软件语言设置为简体中文);

**Comment by manipulative** [comment]
> > mac版本无法进入设置菜单~
> 
> Change the zotero language to Chinese(simple, 将Zotero软件语言设置为简体中文);

wow，awesome，我的问题解决了！谢谢大佬
