### ISSUE TITLE
设置项没有正常出现

### ISSUE THREAD

**Issue by GFDGIT** [MuiseDestiny/zotero-reference#23]
不知道是否zotero beta更新的缘故，设置里标签页没有了，卸载重装也一样，底部的按钮也错位。麻烦看一下，谢谢。

![image](https://user-images.githubusercontent.com/22742500/209763452-b36c8b1e-923d-48ae-83f6-6db15d9d091f.png)

部分错误日志：

```
Security Error: Content at moz-nullprincipal:{fdb6ca25-876f-4ea1-9fa3-54b413ffde7f} may not load or link to chrome://chartero/content/TabPanel/index.html.

Security Error: Content at moz-nullprincipal:{fdb6ca25-876f-4ea1-9fa3-54b413ffde7f} may not load or link to chrome://chartero/content/DataTree/index.html.

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace
Location: jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml
Line Number 12, Column 5:" {file: "jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 12 column: 5 source: "    <html:div style=""}]

version => 6.0.19-beta.9+da392518e, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.19-beta.9+da392518e, extensions => Folder Import for Zotero (0.0.5, extension), Zotero PDF Preview (0.3.7, extension), Background for Zotero Pdf Reader (0.0.2, extension), Zotero Tag (0.3.0, extension), Chartero (1.3.2, extension), Jasminum (0.2.4, extension), Zotero PDF Translate (0.9.8, extension), Zotero Style (1.4.7, extension), Zotero LibreOffice Integration (6.0.3.SA.6.0.19-beta.9+da392518e, extension), Zotero Word for Windows Integration (6.0.2.SA.6.0.19-beta.9+da392518e, extension), Zotero Better Notes (0.8.6, extension), Zotero Reference (0.1.5, extension)
```

**Comment by MuiseDestiny** [comment]
请更新0.1.6，其实出现了，在最后一个，方向键右就会出现对应设置，不过最新版应该自动更改设置宽度。

**Comment by GFDGIT** [comment]
更新0.1.6后设置项正常了。

不过，错误日志里面还是有这一行：
`[JavaScript Error: "XML Parsing Error: prefix not bound to a namespace Location: jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml Line Number 12, Column 5:" {file: "jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 12 column: 5 source: " <html:div style=""}] `

**Comment by MuiseDestiny** [comment]
> 

重启试试，我试了下不会报这个错误，但也有类似错误，可能我是开发环境报错不一样。日后更新会解决这个，目前不影响正常功能使用。

**Comment by GFDGIT** [comment]
重启了，上面的报错没有了。

新的报错是这样的，不过是不影响使用的：

`[JavaScript Error: "tabContainer is null" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 987}]`

**Comment by MuiseDestiny** [comment]
> 重启了，上面的报错没有了。
> 
> 新的报错是这样的，不过是不影响使用的：
> 
> `[JavaScript Error: "tabContainer is null" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 987}]`

这个可以解决，加个判断就好了
