### ISSUE TITLE
zotero最新beta版本中参考文献界面消失

### ISSUE THREAD

**Issue by Tttang123456** [MuiseDestiny/zotero-reference#233]
In zotero 7beta, due to a change in the location of the module in the interface, the reference button that was on the right side now disappears, making it impossible to use this plugin

zotero 7beta中，由于界面中模块位置更改，原本右侧的参考文献按钮现在消失，导致无法使用此插件。插件版本号：0.6.4

<img width="353" alt="image" src="https://github.com/MuiseDestiny/zotero-reference/assets/139727991/77876d62-6e0a-45f1-bd36-03a96ed601b2">

**Comment by Afredxus-java** [comment]
I also have this question.
我也是这个问题。

**Comment by v-jinci** [comment]
I also have this question.
我也是这个问题。有没有什么办法吗，还是要下旧的安装包

**Comment by wsm6636** [comment]
I also have this question.

**Comment by AstroCIEL** [comment]
the same question, after zotero auto-updated and changed its appearance

**Comment by yshhwy** [comment]
我有一个临时解决的方法，不是很优雅，但是能显示出参考文献的侧边栏。
当我用其他插件开启侧边栏，使得其数量为3个的时候，参考文献侧边栏界面就出现了，尽管出现在错误的面板上。但至少暂时使其可用。

![Zotero20240127(1907)@2x](https://github.com/MuiseDestiny/zotero-reference/assets/80385343/4f61296a-5231-413a-8ebb-c36d93adcad1)


如果对你有用或无用，可以讨论讨论。

**Comment by Arclunar** [comment]
> 我有一个临时解决的方法，不是很优雅，但是能显示出参考文献的侧边栏。 当我用其他插件开启侧边栏，使得其数量为3个的时候，参考文献侧边栏界面就出现了，尽管出现在错误的面板上。但至少暂时使其可用。
> 
> ![Zotero20240127(1907)@2x](https://private-user-images.githubusercontent.com/80385343/300173808-4f61296a-5231-413a-8ebb-c36d93adcad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTY5MzcsIm5iZiI6MTcwNjUxNjYzNywicGF0aCI6Ii84MDM4NTM0My8zMDAxNzM4MDgtNGY2MTI5NmEtNTIzMS00MTNhLThlYmItYzM2ZDkzYWRjYWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA4MjM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMmZiZTc2Mzk3NjA3YTdlNzY0ZDA0MzQwMGVlOWUwZGRkN2M1ZGJjMjEyOTg1MjRkNTU0ZDcyMGEyMjNiOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UIF9LBLSq8EjSy7nwJP-UZF-jCwlQNk_ZAnS-9PjGYE)
> 
> 如果对你有用或无用，可以讨论讨论。
@yshhwy 
请问你用的是什么插件打开侧边栏

**Comment by yshhwy** [comment]
> > 我有一个临时解决的方法，不是很优雅，但是能显示出参考文献的侧边栏。 当我用其他插件开启侧边栏，使得其数量为3个的时候，参考文献侧边栏界面就出现了，尽管出现在错误的面板上。但至少暂时使其可用。
> > ![Zotero20240127(1907)@2x](https://private-user-images.githubusercontent.com/80385343/300173808-4f61296a-5231-413a-8ebb-c36d93adcad1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTY5MzcsIm5iZiI6MTcwNjUxNjYzNywicGF0aCI6Ii84MDM4NTM0My8zMDAxNzM4MDgtNGY2MTI5NmEtNTIzMS00MTNhLThlYmItYzM2ZDkzYWRjYWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA4MjM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMmZiZTc2Mzk3NjA3YTdlNzY0ZDA0MzQwMGVlOWUwZGRkN2M1ZGJjMjEyOTg1MjRkNTU0ZDcyMGEyMjNiOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UIF9LBLSq8EjSy7nwJP-UZF-jCwlQNk_ZAnS-9PjGYE)
> > 如果对你有用或无用，可以讨论讨论。
> > @yshhwy
> > 请问你用的是什么插件打开侧边栏

Zotero One，是个作者收费的插件。就是之前的Zotero Pro Max什么的

**Comment by Arclunar** [comment]
您的邮件已收到，谢谢祝好!

**Comment by Arclunar** [comment]
好的，感谢~

**Comment by aqlkzf** [comment]
![image](https://github.com/MuiseDestiny/zotero-reference/assets/67051837/ca17f436-4b77-4003-9b6f-266a554ef9ac)
最新的插件发现 鼠标放在上面是悬浮显示参考文献 不是之前点击在底部或者侧面显示了！  感谢大佬

**Comment by Arclunar** [comment]
您的邮件已收到，谢谢祝好!

**Comment by chichichila** [comment]
> ![image](https://private-user-images.githubusercontent.com/67051837/307708040-ca17f436-4b77-4003-9b6f-266a554ef9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTIwNTQsIm5iZiI6MTcwOTAxMTc1NCwicGF0aCI6Ii82NzA1MTgzNy8zMDc3MDgwNDAtY2ExN2Y0MzYtNGI3Ny00MDAzLTliNmYtMjY2YTU1NGVmOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA1MjkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMGE4M2I5MmY2N2UyYzU1ZDUyZTYyZTQ5ZWVkMGIzNjFhZGNkNmM0NWFhYmE4OTU5MjNkODM4YmQwNDA3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j71MilKURtoFpnxXNvGuqpar1mkSBx2XFfgCy7-ieDI) 最新的插件发现 鼠标放在上面是悬浮显示参考文献 不是之前点击在底部或者侧面显示了！ 感谢大佬

你好啊，这是哪个插件啊？？

**Comment by jianghuchuanshuo** [comment]
同样的问题，没有了侧边栏按钮，该怎么查看参考文献呢？
