### ISSUE TITLE
Zotero 6.0.30版本没办法安装Zotero Reference插件

### ISSUE THREAD

**Issue by Forshining** [MuiseDestiny/zotero-reference#234]

**Comment by Forshining** [comment]
我在build文件夹下下载的xpi没办法安装，请问如何解决
<img width="1003" alt="截屏2024-01-28 00 24 35" src="https://github.com/MuiseDestiny/zotero-reference/assets/91770868/4889f8b0-94c8-484d-96f3-c439735e3cf3">

**Comment by Andy20178** [comment]
下载之前的版本即可，最新版本确实不支持
