### ISSUE TITLE
ctrl+单击跳转浏览器较慢，需10s以上

### ISSUE THREAD

**Issue by ChuGary** [MuiseDestiny/zotero-reference#24]
如题

**Comment by ChuGary** [comment]
另外想问下是否有考虑把ctrl+单击换成右键单击呢，目前右键也闲着。

**Comment by MuiseDestiny** [comment]
> 另外想问下是否有考虑把ctrl+单击换成右键单击呢，目前右键也闲着。

10s应该是crossref接口消耗的，它的确比较慢。
日后可能会换成其他快的接口。

对于参考文献中不包含doi的pdf，速度慢是因为查询文献的doi消耗的，可以变得很快，加载完统统提前查一遍就好了，但是对接口也是一种压力；对于pdf包含doi是瞬间打开的。考虑到浮窗就可以看到文献大部分信息，跳转网页用的也比较少，所以就做成现在这样，在点击时候才查询doi。

因为在浏览器中ctrl单击是在新标签页打开，所以我用了这个逻辑，右键打开也可以的，但是也有人提出要用右键唤醒浮窗。

**Comment by jgu1989** [comment]
在Mac上ctrl+单击无法跳转浏览器，请问可能的原因是什么呢？

**Comment by MuiseDestiny** [comment]
> 在Mac上ctrl+单击无法跳转浏览器，请问可能的原因是什么呢？

没事，下个版本改交互，在浮窗点击也可以跳转
