### ISSUE TITLE
启动本插件后，点击zotero自带浏览器后，PDF视窗分成两屏，无法关闭。且首选项页面消失。

### ISSUE THREAD

**Issue by ecssd** [MuiseDestiny/zotero-reference#25]
您好，插件非常好用。
问题一：但是利用zotero自带浏览器和插件阅读茉莉花自动添加书签的学位论文，或是用acrobat添加过目录的PDF时，点击一下（图一）显示文档大纲的目录，阅览页面就会出现（图二）分屏，且无法按照目录跳转。请问怎么在不禁用插件的情况下，让zotero大纲的目录跳转恢复正常？
图一：
<img width="211" alt="image" src="https://user-images.githubusercontent.com/121597795/209946103-4eedde35-2462-49fc-8273-20359bd32aa1.png">

图二：
<img width="896" alt="image" src="https://user-images.githubusercontent.com/121597795/209946226-611bb61d-951e-4352-b51f-098679ed108b.png">

问题二：首选项页面，reference的页面消失（图三）。
图三：
<img width="800" alt="image" src="https://user-images.githubusercontent.com/121597795/209946417-46eff1d9-c1d7-4c45-b644-61563a3b3674.png">

**Comment by MuiseDestiny** [comment]
问题一属于bug了，我尽快修复。问题二，因为插件比较多，可以点击首选项顶栏最后一个插件按方向→到达ref的设置。

**Comment by MuiseDestiny** [comment]
问题一属于bug了，我尽快修复。问题二，因为插件比较多，可以点击首选项顶栏最后一个插件按方向→到达ref的设置。

**Comment by MuiseDestiny** [comment]
zotero6首选项可能是有最大宽度，zotero7会调整首选项排版就不会出现问题二了。

**Comment by MuiseDestiny** [comment]
更新解决问题，初衷是修改pdf内部链接在分割窗口打开，避免看完图公式再点击”后退“，没想到目录也被修改了。现在即使开启修改链接，目录也不会被修改，如果也不想修改PDF内部跳转，首选项也可以关闭。如有问题可再打开这个issue。

**Comment by ecssd** [comment]
！谢谢作者大大！问题二我后来发现重启电脑可以修复！
