### ISSUE TITLE
参考文献每次都只能抓取一篇出来

### ISSUE THREAD

**Issue by chenhengzh** [MuiseDestiny/zotero-reference#254]
<img width="1508" alt="Screenshot 2024-03-21 at 14 47 23" src="https://github.com/MuiseDestiny/zotero-reference/assets/74190205/59659f64-b50c-4a68-adc7-fdb4a2e454a7">

**Comment by Endless-jc** [comment]
我也遇到了，不知道怎么解决

**Comment by MuiseDestiny** [comment]
已解决，更新到0.7.7，zo内官方渠道检查更新。
