### ISSUE TITLE
点击链接分页功能的小bug

### ISSUE THREAD

**Issue by chenhengzh** [MuiseDestiny/zotero-reference#255]
现在点击目录链接也会自动分页。希望这一功能只针对文档内的链接

**Comment by tjuyyz** [comment]
解决方案请参考：[使用zotero点击参考文献就会分成上下两个屏](https://blog.csdn.net/jiaxiaovi/article/details/136473095)

**Comment by chenhengzh** [comment]
我需要点击文档内链接分屏这个功能，但是不需要点击目录也分屏

**Comment by MuiseDestiny** [comment]
已知bug 勿催

**Comment by MuiseDestiny** [comment]
已修复，zo内检查更新，或在https://gitee.com/MuiseDestiny/plugins
