### ISSUE TITLE
partner.semanticscholar.org 现已弃用 请确保在所有URL中将其替换为“api.semanticscholar.org”。

### ISSUE THREAD

**Issue by NathanaelCat** [MuiseDestiny/zotero-reference#256]
partner.semanticscholar.org 现已弃用
请确保在所有URL中将其替换为“api.semanticscholar.org”。

另，zotero7的0.7.5版本中点击文献旁的+号没有反应，import不了文献

**Comment by MuiseDestiny** [comment]
`partner.semanticscholar.org`从未使用过

导入不了请手动导入。
