### ISSUE TITLE
在MAC上好像没适配

### ISSUE THREAD

**Issue by jsrdcht** [MuiseDestiny/zotero-reference#257]
在上栏没有插件对应的引号按钮。
![image](https://github.com/MuiseDestiny/zotero-reference/assets/22300065/ef8ca28b-a377-4656-9f95-9a4fc68370b8)
且鼠标悬浮在正文的引用时出现的窗口和以前的版本差不多

**Comment by MuiseDestiny** [comment]
确保zo最新，插件是0.7.7
