### ISSUE TITLE
点击参考文献标题不能复制

### ISSUE THREAD

**Issue by clamon4617** [MuiseDestiny/zotero-reference#266]
作者你好，感谢你对这款插件的开发和维护。
升级到win11 7.0.0-beta.73+398454f85 (64-bit）版本后，原先在阅读文献是，点击文献标题即可复制，现在点击虽然提示已复制，但粘贴并无效果。zotero中其他位置复制粘贴正常。

**Comment by MuiseDestiny** [comment]
已修复 在zo内检查更新。0.8.1，或从：https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-reference.xpi

**Comment by clamon4617** [comment]
感谢修复，祝好！

**Comment by clamon4617** [comment]
不好意思，升级0.81后参考功能按钮不出现，又回滚0.75了
