### ISSUE TITLE
zotero reference最新0.7.5右键无法显示菜单

### ISSUE THREAD

**Issue by yufusang** [MuiseDestiny/zotero-reference#272]
大佬您好，zotero beta.74,windows，最新的reference插件显示参考文献后右键菜单无法显示，希望修复，谢谢！

**Comment by MuiseDestiny** [comment]
ref最新是0.8.2 请关注gitee更新
https://gitee.com/MuiseDestiny/plugins

或在zo内检查更新

**Comment by yufusang** [comment]
好的谢谢大佬，已更新到最新版，但是reference 图标消失了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Polygon ***@***.***&gt;
发送时间: 2024年4月16日 12:44
收件人: MuiseDestiny/zotero-reference ***@***.***&gt;
抄送: yufusang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [MuiseDestiny/zotero-reference] zotero reference最新0.7.5右键无法显示菜单 (Issue #272)





 
Closed #272 as completed.

**Comment by MuiseDestiny** [comment]
多重启
