### ISSUE TITLE
浮窗信息与参考文献不匹配到此反馈

### ISSUE THREAD

**Issue by MuiseDestiny** [MuiseDestiny/zotero-reference#28]
目前依靠readpaper，arXiv等接口获取参考文献的详细信息，对于部分文献匹配会错误，如果你的研究领域频繁出错，请在此提出并提出解决方案。

解决方案意思是，人拿到这个参考文献如`[1] xxxxxx`，该怎么查找才能找到与之对应的摘要等信息。然后我让插件实现。如果人工搜索都很难找到不必提出。也可以反馈一个类似readpaper的搜索引擎（它可以搜到的结果>readpaper）。

例如 [8] 任红轩.国家纳米科学中心.热电材料在能源中的应用.新材料产业, 2006,(5):65-67
在知网搜索`国家纳米科学中心.热电材料在能源中的应用.新材料产业`可找到它的摘要信息。（知网已计划，不必再次反馈）

**Comment by isPengLu** [comment]
参考文献内是[16] Hammond, M. (2009)  Immediate Response , London: Michael Joseph.
浮窗显示的是Life on the Edge: The Cistercian Abbey of Balmerino, Fife (Scotland)

原文献是Dant, Tim. “Drivers and Passengers.” In The Routledge Handbook of Mobilities, edited by Peter Adey, David Bissell, Kevin Hannam, Peter Merriman, and Mimi Sheller, 0 ed., 367–75. Routledge, 2014. https://doi.org/10.4324/9781315857572.

**Comment by MuiseDestiny** [comment]
> [16] Hammond, M. (2009) Immediate Response , London: Michael Joseph.

请问有了这一段文本`[16] Hammond, M. (2009) Immediate Response , London: Michael Joseph.`，在哪里（网站）搜索其中的什么关键词可以得到`Dant, Tim. “Drivers and Passengers.” In The Routledge Handbook of Mobilities, edited by Peter Adey, David Bissell, Kevin Hannam, Peter Merriman, and Mimi Sheller, 0 ed., 367–75. Routledge, 2014. https://doi.org/10.4324/9781315857572.`呢。

我搜索` In The Routledge Handbook of Mobilities`可以搜索到，但当仅仅知道`[16] Hammond, M. (2009) Immediate Response , London: Michael Joseph.`确实很难搜索到。
![image](https://user-images.githubusercontent.com/51939531/210350182-8daa22f2-f5f8-44f6-8913-b2d4e8649356.png)

或者说pdf中有其它信息，插件匹配到的`[16] Hammond, M. (2009) Immediate Response , London: Michael Joseph.`是不全的。

**Comment by isPengLu** [comment]
抱歉，我当时的表述非常精简，甚至有些过分，我的意思是其实在如下的图中就可以反映到：
<img width="1311" alt="截屏2023-01-03 13 06 42" src="https://user-images.githubusercontent.com/44140709/210354294-64a24c2b-a4d7-48d6-adb9-b063aa46354a.png">

右侧的16号线是的内容是正确的，但浮窗的内容是错误的，原文献指的是正在阅读的文献。

PDF：
[Dant_2014_Drivers and Passengers.pdf](https://github.com/MuiseDestiny/zotero-reference/files/10336407/Dant_2014_Drivers.and.Passengers.pdf)

抱歉给您造成误解 😖
