### ISSUE TITLE
中文文献报错，未找到fileName

### ISSUE THREAD

**Issue by CodeTestHome** [MuiseDestiny/zotero-reference#287]
zotero版本：beta78/beta99(为排除zotero版本问题下载了99的zip版本进行尝试，问题依旧存在）
reference：0.91
![image](https://github.com/user-attachments/assets/d3d4c7b1-570e-4054-88e7-bc5d02d34f62)
中文文献，包含之前能够找到部分（即不全）的文章都报错”未找到fileName“。目前尝试英文文献，beta78版本显示parse，beta99英文正常
debug日志：
        (3)(+0016103): [Ethereal Reference] 在CNKI中检索文献...
        (3)(+0000001): HTTP POST "QueryJson={"Platform":"","Resource":"CROSSDB","Classid":"WD0FTY92","Products":"","QNode":{"QGroup":[{"Key":"Subject","Title":"","Logic":0,"Items":[],"ChildItems":[{"Key":"input[data-tipid=gradetxt-1]","Title":"篇名","Logic":0,"Items":[{"Key":"input[data-tipid=gradetxt-1]","Title":"篇名","Logic":0,"Field":"TI","Operator":"DEFAULT","Value":"水平循环荷载下砂土中管桩动力响应研究","Value2":""}],"ChildItems":[]}]},{"Key":"ControlGroup","Title":"","Logic":0,"Items":[],"ChildItems":[]}]},"ExScope":"1","SearchType":1,"Rlang":"CHINESE","KuaKuCode":"YSTT4HG0,LSTPFY1C,JUP3MUPD,MPMFIG1A,EMRPGLPA,WQ0UVIAA,BLZOG7CK,PWFIRAGL,NN3FJMUV,NLBO1Z6R"}" to https://kns.cnki.net/kns8s/brief/grid
        (5)(+0000008): CookieSandbox: Being paranoid about channel for kns.cnki.net
        (5)(+0000000): CookieSandbox: Cleared cookies to be sent to kns.cnki.net
        (5)(+0000361): CookieSandbox: Being paranoid about channel for kns.cnki.net
        (5)(+0000000): CookieSandbox: Not tracking received cookies for kns.cnki.net
        (3)(+0000000): HTTP POST https://kns.cnki.net/kns8s/brief/grid succeeded with 200
        (3)(+0000001): HTTP GET https://kns.cnki.net/kcms2/article/abstract?v=Xlf5kQqXAOmqI9LiIv7jSFqU51Vk8vmohO8w1SLLB6ZayddhwWs0hsfX2djEAH6P2X6VEpzsx91QYmatT4nx-AJycsDL07SDZlTEUFK3hbRACOUCdtuUMSo5h--xB8dsgSKOpNErHuAnFuo7_KOG2XfpiwYx_NCn&uniplatform=NZKPT&language=CHS
        (5)(+0000004): CookieSandbox: Being paranoid about channel for kns.cnki.net
        (5)(+0000000): CookieSandbox: Cleared cookies to be sent to kns.cnki.net
        (5)(+0000190): CookieSandbox: Being paranoid about channel for kns.cnki.net
        (5)(+0000000): CookieSandbox: Not tracking received cookies for kns.cnki.net
        (3)(+0000019): HTTP GET https://kns.cnki.net/kcms2/article/abstract?v=Xlf5kQqXAOmqI9LiIv7jSFqU51Vk8vmohO8w1SLLB6ZayddhwWs0hsfX2djEAH6P2X6VEpzsx91QYmatT4nx-AJycsDL07SDZlTEUFK3hbRACOUCdtuUMSo5h--xB8dsgSKOpNErHuAnFuo7_KOG2XfpiwYx_NCn&uniplatform=NZKPT&language=CHS succeeded with 200
        (3)(+0002184): [Ethereal Reference] Fail
![image](https://github.com/user-attachments/assets/ec3520f5-e9c9-4554-9a9f-2c9c7ba32beb)

**Comment by 2000pl** [comment]
zotero：7.0.0-beta.99+174bde745 (64-bit)；reference：0.89，也出现这种情况。

**Comment by Sephdex** [comment]
7.0.0-beta.101+220bb4383 (64-bit); reference：0.92，也出现这种情况

**Comment by 12qweas** [comment]
7.0.0-beta.101+220bb4383（64-bit）;reference：0.9.3,也出现这种情况

**Comment by MuiseDestiny** [comment]
耐心等待插件适配，知网改版
