### ISSUE TITLE
希望出一个文献图谱功能，显示zotero中的文献关联关系

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-reference#3]
reference可以将抓取的文献自动关联起来，如果可以将这些关联的文献以图谱的形式展现出来，使用起来就更直观了。最好能像obsidian的关系图谱一样，有各种选项、功能，既能看到zotero整体所有文献的引用关系，也能看到每个文献的关系，也能进行文献的筛选。

**Comment by volatile-static** [comment]
Chartero已经有了啊
