### ISSUE TITLE
mac 中弹窗无法选中文字 + 无法翻译

### ISSUE THREAD

**Issue by jiang-dh** [MuiseDestiny/zotero-reference#30]
软件信息：6.0.19
电脑信息：Mac 13.1 (22C65)

在使用插件过程中遇到以下问题：
1. 首选项和工具选项中并没有出现 zotero-reference的设置栏；
2. 在文中直接点击参考文献索引，会在下方出现参考文献页面，但是**参考文献页面会一直存在**（如下图），无法去除；
3. 在参考文献弹窗中**无法选中文字**，同时也**无法翻译**（已安装 translate）
<img width="500" alt="1" src="https://user-images.githubusercontent.com/59220893/210483378-f0d92ebf-a81e-42dc-b0ed-22ea5ef90b56.png">

**Comment by MuiseDestiny** [comment]
1. 参考[可能插件太多被挤到最后了](https://github.com/MuiseDestiny/zotero-reference/issues/23)
2. 可以试试重新下载插件xpi重新安装，或者在首选项设置它的消失时间（解决问题1后）
3. 按住ctrl点击摘要会翻译，但选不中文字这个可能无法帮到你，我目前没有可以测试的mac

**Comment by CMD-cmd** [comment]
我的也是 mac，在参考文献弹窗中是可以选中文字的，也可以复制到别的软件里面翻译，但是 `ctrl`+点击标题和摘要都无法翻译（已安装 PDF translate 插件）
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/79133756/215107323-ecc32b2a-626e-4d25-9d52-d6ffeb117041.png">
安装的插件如图：
<img width="823" alt="image" src="https://user-images.githubusercontent.com/79133756/215107632-51ca4bbd-6fec-4fc7-872f-1894dc37d8ee.png">

**Comment by wangxiaodong1021** [comment]
同样的问题，已经安装最新的插件，还是不能弹窗ctrl点击翻译

**Comment by MuiseDestiny** [comment]
> 同样的问题，已经安装最新的插件，还是不能弹窗ctrl点击翻译

可能是ctrl键只在window有，不跨平台，改成shift点击试试

**Comment by MuiseDestiny** [comment]
@CMD-cmd @wangxiaodong1021 
https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.2.7
有时间，下载测试下

**Comment by wangxiaodong1021** [comment]
感谢及时回复，刚刚测试用command+点击可以翻译了

**Comment by MuiseDestiny** [comment]
> 感谢及时回复，刚刚测试用command+点击可以翻译了

好的
