### ISSUE TITLE
zotero 7.0.5 版本插件图标消失，设置中无相关选项

### ISSUE THREAD

**Issue by MBJinX** [MuiseDestiny/zotero-reference#313]
相同问题出现于GPT插件，但是zotero style正常
![image](https://github.com/user-attachments/assets/65894566-9fa8-43c4-9452-2bdd6fc570ce)
![image](https://github.com/user-attachments/assets/c8a161d3-075c-47b0-b5ab-d9ad5a1e8170)

**Comment by MuiseDestiny** [comment]
覆盖安装下呢

**Comment by MBJinX** [comment]
> 覆盖安装下呢

已经尝试过完全卸载zotero后再次安装，但还是不行。

今早我是从zotero6直接升级zotero7，然后发现了这个问题，已经尝试过完全重装软件、卸载插件后重装插件，均没有效果

**Comment by MuiseDestiny** [comment]
cmd执行 `<zotero.exe路径> -p`新建一个profile 然后装插件即可

**Comment by MBJinX** [comment]
> cmd执行 `<zotero.exe路径> -p`新建一个profile 然后装插件即可

已成功，感谢作者大大
