### ISSUE TITLE
鼠标放到参考文献的标注上只能弹出一个基础的参考文献信息

### ISSUE THREAD

**Issue by ZhaoJunnNie** [MuiseDestiny/zotero-reference#325]
鼠标放到参考文献的标注上只能弹出一个基础的参考文献，不能像B站视频上那样在弹出的参考文献信息窗口上停一会触发一个包含参考文献摘要等等的新窗口
<img width="735" alt="iShot_2024-10-16_14 53 04" src="https://github.com/user-attachments/assets/c234d867-d067-4ca0-8d29-c06abe5c993a">

Zotero: 7.0.7
Zotero Reference: 1.2.2
System: Macos 14.6.1

**Comment by aflyingnoob** [comment]
请问你弄好了吗
