### ISSUE TITLE
堆叠试图显示bug

### ISSUE THREAD

**Issue by isPengLu** [MuiseDestiny/zotero-reference#33]
堆叠试图浮窗显示有问题，如图：

<img width="1728" alt="截屏2023-01-05 20 34 39" src="https://user-images.githubusercontent.com/44140709/210866544-b60c9131-4ccb-4a5b-809e-60cb1146e574.png">

虽然不常用这个视图，但确实是个Bug。

**Comment by MuiseDestiny** [comment]
怎么做到侧边栏放到下面的

**Comment by isPengLu** [comment]
Mac系统下是这么设置的，win应该也差不多，改变布局方式

<img width="465" alt="截屏2023-01-06 08 26 47" src="https://user-images.githubusercontent.com/44140709/210951762-eddb2d1f-d3e2-4e51-bde2-ed9f3df1ca0d.png">

**Comment by MuiseDestiny** [comment]
好吧，我竟然刚知道。这样的话在条目上面显示可以不。

**Comment by isPengLu** [comment]
不太懂您说的条目上面显示是啥意思。

我看到的主要的问题就是PDF阅读界面上的关联文献和参考文献两个栏目中由鼠标指针hover触发的浮窗还是往左边去，一部分会被裁掉。

**Comment by MuiseDestiny** [comment]
> 不太懂您说的条目上面显示是啥意思。
> 
> 我看到的主要的问题就是PDF阅读界面上的关联文献和参考文献两个栏目中由鼠标指针hover触发的浮窗还是往左边去，一部分会被裁掉。

现在是左边因为参考文献在右边，你的视图在下面所以浮窗在上面显示

**Comment by isPengLu** [comment]
现在的问题就是 您说的浮窗在上面显示并没有实现，还是在左侧：
<img width="1103" alt="截屏2023-01-06 12 14 11" src="https://user-images.githubusercontent.com/44140709/211001512-eea5ae1d-d35f-4e60-9446-704f17c8545c.png">

**Comment by isPengLu** [comment]
不过这样的视图只是偶尔用用，优先级不是很高

**Comment by MuiseDestiny** [comment]
想了一下这种视图没法优化，如果放在选中条目上面，会遮挡上一个条目，鼠标无法正常选择。
如果放在整个tab上面，鼠标移动到浮窗会经过其他条目，浮窗内容就变了。
