### ISSUE TITLE
浮窗大小适配屏幕

### ISSUE THREAD

**Issue by Chauncy-Eliot** [MuiseDestiny/zotero-reference#34]
首先感谢作者的插件，真的很实用！
然后是有一个问题：我的电脑因为调节了全局的图标和字体大小，导致现在浮窗没有版权完全显示在窗口，而是会有部分在屏幕之外，像这样：
![image](https://user-images.githubusercontent.com/119091436/211145045-ea472c55-dc73-4900-bf34-6adef2ac6769.png)
请问可以调节浮窗来适配屏幕吗？

**Comment by MuiseDestiny** [comment]
已经修复了这个问题，新版本重写了弹窗，还没发布，有一个储存的小问题。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/211146446-75052dd0-f48c-41ed-9ccf-b639ab7c12fe.png)

**Comment by Chauncy-Eliot** [comment]
收到，期待新版本！感谢！
