### ISSUE TITLE
参考文献保存到和ZoteroStyle一样的独立笔记中（或者是同一个独立笔记中），而不是“其它”字段

### ISSUE THREAD

**Issue by Geo123abc** [MuiseDestiny/zotero-reference#35]
现在是保存参考文献到`其它/Extra`字段下，但是考虑到“参考文献”内容太多，导致信息栏太长了，是否考虑和ZoteroStyle一样保存到一个笔记中，或者和ZoteroStyle一样保存到同一个独立笔记中？不知道这个难度大不大？

**Comment by MuiseDestiny** [comment]
可以的，陆续会实现。目前`其它`字段实现起来相对简单。

但是，存笔记可能会有很多bug，比如污染笔记环境，总是弹窗同步冲突，等解决了会存到这里。

我觉得，小量数据存`其它`是没问题的，参考文献的确有点多了。

**Comment by Geo123abc** [comment]
我是这样想的，反正ZoteroStyle已经污染笔记环境了（我目前是把ZoteroStyle产生的笔记放在回收站），再加上 zotero-reference，也没啥吧，感觉总比笔记和字段都污染要好一些，期待越来越好，赞！

**Comment by MuiseDestiny** [comment]
> 我是这样想的，反正ZoteroStyle已经污染笔记环境了（我目前是把ZoteroStyle产生的笔记放在回收站），再加上 zotero-reference，也没啥吧，感觉总比笔记和字段都污染要好一些，期待越来越好，赞！

哈哈哈，反正已经污染了

**Comment by zyx335588** [comment]
似乎“其它”字段允许保存的字符数，要比笔记小一些，字符超限后也会阻止同步。
![Snipaste_2023-01-10_15-01-03](https://user-images.githubusercontent.com/22871049/211485083-4e88eb81-2fe0-4afc-958d-b0f9cf5ebb84.png)

后期是不是也可以像BBT那样单独保存本地数据。不过BBT自己维护了一个数据库文件，reference也许可以考虑在zotero的数据文件夹中直接保存本地文本文件。

**Comment by MuiseDestiny** [comment]
> 似乎“其它”字段允许保存的字符数，要比笔记小一些，字符超限后也会阻止同步。 ![Snipaste_2023-01-10_15-01-03](https://user-images.githubusercontent.com/22871049/211485083-4e88eb81-2fe0-4afc-958d-b0f9cf5ebb84.png)
> 
> 后期是不是也可以像BBT那样单独保存本地数据。不过BBT自己维护了一个数据库文件，reference也许可以考虑在zotero的数据文件夹中直接保存本地文本文件。

请问这个冲突，大概有多少条参考文献。参考文献确实太大了，不能放这里了。

**Comment by zyx335588** [comment]
> > 似乎“其它”字段允许保存的字符数，要比笔记小一些，字符超限后也会阻止同步。 ![Snipaste_2023-01-10_15-01-03](https://user-images.githubusercontent.com/22871049/211485083-4e88eb81-2fe0-4afc-958d-b0f9cf5ebb84.png)
> > 后期是不是也可以像BBT那样单独保存本地数据。不过BBT自己维护了一个数据库文件，reference也许可以考虑在zotero的数据文件夹中直接保存本地文本文件。
> 
> 请问这个冲突，大概有多少条参考文献。参考文献确实太大了，不能放这里了。

这篇综述有大约160篇参考文献

**Comment by Geo123abc** [comment]
应该是字符数限制吧，找个大点的txt试一下,看看能装下多少字符
