### ISSUE TITLE
搜索功能失效

### ISSUE THREAD

**Issue by hanlu-nju** [MuiseDestiny/zotero-reference#37]
插件更新到0.2.1版本之后，在参考文献中搜索的功能失效了，使用任何关键词结果都是空的

**Comment by MuiseDestiny** [comment]
> 插件更新到0.2.1版本之后，在参考文献中搜索的功能失效了，使用任何关键词结果都是空的

我竟然没测试这个东西

**Comment by MuiseDestiny** [comment]
> 插件更新到0.2.1版本之后，在参考文献中搜索的功能失效了，使用任何关键词结果都是空的

可以了，0.2.2

**Comment by hanlu-nju** [comment]
> > 插件更新到0.2.1版本之后，在参考文献中搜索的功能失效了，使用任何关键词结果都是空的
> 
> 可以了，0.2.2

感谢大佬
