### ISSUE TITLE
ctrl+单击蓝色区域 -> 用默认浏览器打开文献地址；这个功能用不了

### ISSUE THREAD

**Issue by csf2022scut** [MuiseDestiny/zotero-reference#38]
crtl单击蓝色区域后默认浏览器没有打开文献地址

**Comment by MuiseDestiny** [comment]
> crtl单击蓝色区域后默认浏览器没有打开文献地址

发一下PDF，描述下第几条参考文献有问题呢

**Comment by csf2022scut** [comment]
> > crtl单击蓝色区域后默认浏览器没有打开文献地址
> 
> 发一下PDF，描述下第几条参考文献有问题呢

都不行啊。。。点击后右下角都显示一下[pending] Request URL from API但是都不会跳转

**Comment by csf2022scut** [comment]
> > crtl单击蓝色区域后默认浏览器没有打开文献地址
> 
> 发一下PDF，描述下第几条参考文献有问题呢

都不行啊。。。 点击后右下角都显示一下[pending] Request URL from API但是都不会跳转

**Comment by MuiseDestiny** [comment]
> > > crtl单击蓝色区域后默认浏览器没有打开文献地址
> > 
> > 
> > 发一下PDF，描述下第几条参考文献有问题呢
> 
> 都不行啊。。。 点击后右下角都显示一下[pending] Request URL from API但是都不会跳转

重新下载安装下最新版，看了下是少写了个东西，ctrl+点击应该是正常的

**Comment by csf2022scut** [comment]
> > > > crtl单击蓝色区域后默认浏览器没有打开文献地址
> > > 
> > > 
> > > 发一下PDF，描述下第几条参考文献有问题呢
> > 
> > 
> > 都不行啊。。。 点击后右下角都显示一下[pending] Request URL from API但是都不会跳转
> 
> 重新下载安装下最新版，看了下是少写了个东西，ctrl+点击应该是正常的

试了一下有些文献还是可以的，谢谢！
