### ISSUE TITLE
“PDF内链接在分割窗口跳转“功能没有正确跳转

### ISSUE THREAD

**Issue by hanlu-nju** [MuiseDestiny/zotero-reference#39]
版本0.2.1，如果关掉此功能的话可以跳转到正确位置，但是开启此功能后只会另外开启一个分割窗口，显示的还是链接的位置，而不是链接应该跳转到的位置。而且分割窗口存在的话，点击链接后分割窗口没有反应。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/211838022-9f6a679d-c8a4-4b9e-a675-fddef3fd9830.png)
我测试可以的，是所有PDF跳转都不正常嘛

**Comment by hanlu-nju** [comment]
我试了一下，好像也不是所有的都有问题，这是出问题的一个[pdf](http://proceedings.mlr.press/v108/khemakhem20a/khemakhem20a.pdf)

**Comment by MuiseDestiny** [comment]
好的，可能比较特殊，我看看

**Comment by MuiseDestiny** [comment]
已解决，重新安装最新版
