### ISSUE TITLE
如果双击参开文献列表的文献，自动跳转该文献网页就好了

### ISSUE THREAD

**Issue by zhengnan365** [MuiseDestiny/zotero-reference#4]
如果双击参开文献列表的文献，自动跳转该文献网页就好了

**Comment by zyx335588** [comment]
非常感谢作者插件，期待添加此功能。
如果可以，作者是否考虑在点击右侧面板的参考文献条目时添加弹出菜单，类似信息面板“标题”（“URL“、“DOI”）那样，把“打开网页”、“保存条目并查找可用PDF”等功能整合进去就更好了。

**Comment by ChuGary** [comment]
同感，非常需要这个功能，因为很多时候只是想稍微看看这个参考文献讲的什么，并不想下载，不然会“污染”自己的文献库

**Comment by MuiseDestiny** [comment]
那就做！

**Comment by ChuGary** [comment]
> 那就做！

感谢，我觉得这个插件的主要使用场景是在精读一篇文章时，很多时候看一些段落引用的文献，需要滑动到底端的参考文献列表，复制到浏览器搜索，再滑回来，这样反复操作真的很麻烦。这个插件就能节省太多时间了，直接在右侧窗口就能跳转或下载。

但是，基于这个使用场景，我个人觉得比较需要增加的功能是：
1）给每篇文献增加索引参考文献的开关，因为大部分文献都不是精读，并不需要看具体的参考文献。例如，可以在现在的右侧栏的这个参考文献列表加一个开关，点击一次索引一次。
2）不知道目前右侧列表的引用文献是否确定能列出所有的参考文献，如有遗漏，会导致想找参考文献的时候编码对不上。所以希望加一个核对或提示的功能。不过如果是按另一个issue中所提的用semanticscholar的API，应该不存在这个问题。

**Comment by MuiseDestiny** [comment]
不会漏，从pdf直接解析的。api一般不准的，最准的还是pdf本身提供的信息。

**Comment by MuiseDestiny** [comment]
> > 那就做！
> 
> 感谢，我觉得这个插件的主要使用场景是在精读一篇文章时，很多时候看一些段落引用的文献，需要滑动到底端的参考文献列表，复制到浏览器搜索，再滑回来，这样反复操作真的很麻烦。这个插件就能节省太多时间了，直接在右侧窗口就能跳转或下载。
> 
> 但是，基于这个使用场景，我个人觉得比较需要增加的功能是： 1）给每篇文献增加索引参考文献的开关，因为大部分文献都不是精读，并不需要看具体的参考文献。例如，可以在现在的右侧栏的这个参考文献列表加一个开关，点击一次索引一次。 2）不知道目前右侧列表的引用文献是否确定能列出所有的参考文献，如有遗漏，会导致想找参考文献的时候编码对不上。所以希望加一个核对或提示的功能。不过如果是按另一个issue中所提的用semanticscholar的API，应该不存在这个问题。


（1）当前逻辑是打开一篇文献，插件自动点击刷新，第一条功能很好实现，不自动刷新就可以了。但是从PDF解析文献很快，几乎无感；
（2）我觉得最准的获取参考文献的api是crossref，semanticscholar我尝试了几个，数量跟PDF对不上。至于提示，单击一个条目，会有弹窗，DOI+标题。以及复制整个条目的信息。

现在先把`ctrl+鼠标点击`跳转浏览器做出来。

**Comment by zyx335588** [comment]
> 不会漏，从pdf直接解析的。api一般不准的，最准的还是pdf本身提供的信息。

是否可以在“刷新”按钮旁边增加一个 强制使用API 获取参考文献的按钮，因为我发现有些PDF文档解析获得的参考文献不全，而此时可能插件认为PDF解析成功，不再使用API获取。

例如[这篇文献](https://www.mdpi.com/1422-0067/23/5/2715)，我这儿PDF只能解析到2篇参考文献，但是crossref的api可以获取到所有的参考文献。

**Comment by MuiseDestiny** [comment]
> > 不会漏，从pdf直接解析的。api一般不准的，最准的还是pdf本身提供的信息。
> 
> 是否可以在“刷新”按钮旁边增加一个 强制使用API 获取参考文献的按钮，因为我发现有些PDF文档解析获得的参考文献不全，而此时可能插件认为PDF解析成功，不再使用API获取。
> 
> 例如[这篇文献](https://www.mdpi.com/1422-0067/23/5/2715)，我这儿PDF只能解析到2篇参考文献，但是crossref的api可以获取到所有的参考文献。

可以的，是这么计划的，第一次用pdf结果，如果点刷新就用API

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/208233105-8af345b9-03a9-491c-a5a8-9f061f7d397f.png)
![image](https://user-images.githubusercontent.com/51939531/208233132-25a4509d-19bb-4599-94b4-c9c19db2a4b4.png)

修复了，（重新安装最新版本即可，不是在zotero里点更新），因为pdf解析是我根据部分pdf写的，可能有些pdf不适配，反馈给我适配就可以了。

我现在还是想把从pdf解析做好，因为api获取的信息支离破碎的。
谢谢你的建议，后面会这么做的。

**Comment by zyx335588** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/208233105-8af345b9-03a9-491c-a5a8-9f061f7d397f.png) ![image](https://user-images.githubusercontent.com/51939531/208233132-25a4509d-19bb-4599-94b4-c9c19db2a4b4.png)
> 
> 修复了，（重新安装最新版本即可，不是在zotero里点更新），因为pdf解析是我根据部分pdf写的，可能有些pdf不适配，反馈给我适配就可以了。
> 
> 我现在还是想把从pdf解析做好，因为api获取的信息支离破碎的。 谢谢你的建议，后面会这么做的。

@MuiseDestiny   谢谢 🌹🌹🌹

API获得信息确实比较凌乱，尤其crossref中参考文献的信息内容很不统一，大部分可能需要根据获取的doi进行二次查询，但是crossref本身还有限制。对于需要通过API获取的参考文献，后期可以考虑查询后进行本地保存CSL JSON，类似zoteroStyle那样，减少API的访问限制。这些都不重要，目前已经很好了，谢谢！

目前，个人感觉影响体验的一点儿是：现在的面板显示的内容很少。
正如 @ChuGary 所言，这个插件可以在阅读文献正文时快速查看正文的参考文献内容。但是，现在右侧面板显示的内容其实非常有限，在通常的面板大小下只能大致看到作者，题目信息，如您上图所示；要想看到更多内容需要将面板调整到非常大，这样极大的限制了快速了解参考信息的目的，尤其对于小屏幕而言。
如果能在鼠标悬停在文献条目上时，鼠标提示显示更多信息；或者点击条目的提示信息，能显示更多信息（目前点击提示仅显示部分内容，其余的省略了，而且显示时间略短），这样就可以更迅速的了解文献信息了，从而决定是否去详情页面查看更详细的信息。

**Comment by MuiseDestiny** [comment]
对很不统一，有的缺doi有的缺标题。

你说的查看文献详情我想想怎么交互，会做出来的。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/208271883-9aa563f4-5833-4ed5-88ff-e566c73d4674.png)
只要鼠标放在条目上，信息框永远不会消失。
现在是一种方案，还想了几种
![image](https://user-images.githubusercontent.com/51939531/208271897-7e24e6a9-1db8-4b9c-9bc7-028a395c077f.png)
比如这个框变宽，紧跟着条目显示。
![image](https://user-images.githubusercontent.com/51939531/208271907-8019717b-b694-45fb-a784-e4b6ed7ff57a.png)
或者添加一个>按钮，点击展开更多信息。

目前把最好实现的实现了（下个版本发，解决#7一起）。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/208280938-e27aef10-d19c-4994-819b-8a54b1c335df.png)
第二种
