### ISSUE TITLE
跳转的分栏窗口怎么关闭？

### ISSUE THREAD

**Issue by yunus-sun** [MuiseDestiny/zotero-reference#40]
插件特别好用，谢谢作者~，想请问一下跳转的分栏窗口是怎么关闭的？

**Comment by MuiseDestiny** [comment]
> 插件特别好用，谢谢作者~，想请问一下跳转的分栏窗口是怎么关闭的？

右键，取消勾选->“水平分割”

**Comment by iseesaw** [comment]
想要一个快捷键，但是在 Zotilo 没有……

**Comment by MuiseDestiny** [comment]
> 

即将可以实现
