### ISSUE TITLE
参考文献详情页加载不出来以及分栏快速跳转后如何关闭？

### ISSUE THREAD

**Issue by chenhaishun** [MuiseDestiny/zotero-reference#41]
![image-20230112224135030](https://cdn.jsdelivr.net/gh/chenhaishun/test_pic@master/typora202301/12/224136-319746.png)
长时间加载不出来详情信息，请问是哪里的问题？（梯子已经打开）
另外麻烦问下，分栏快速跳转后如何关闭呢？
谢谢作者！

**Comment by MuiseDestiny** [comment]
右键 取消勾选 `水平分割`，是所有都无法加载嘛，还是个别，个别的话发一下出问题的PDF。

**Comment by chenhaishun** [comment]
已经解决了PDF显示问题，谢谢作者！
