### ISSUE TITLE
[Pending] Zotero Reference 好像不会自动消失？

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-reference#42]
问题1：打开PDF时出现的这个框似乎不点击就不会消失，感觉可以让他设置多少秒后自己消失嘛？<img width="334" alt="image" src="https://user-images.githubusercontent.com/68216639/212280166-932d50c6-461d-4b1a-ae49-6cf323351ccd.png">

建议1：今天惊喜的发现有推荐关联文献功能了，大赞，可以把自己文献库里的关联起来了。而且还可以有悬浮窗看指定关联文献的基本信息。不过觉得还可以再让使用者爽一点，就是对已经关联的文献也能悬停出现信息框（也即已经（-）的）。
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/68216639/212281323-3b6836ba-8cbf-4f71-9955-1cb7ac2af401.png">
如图，目前对已经关联的文献悬停不会出现悬浮框。

问题2：不太明白推荐关联的文献是基于什么逻辑推荐的呀？是被引和引用嘛？还是只是从引用里基于某一逻辑推荐的？

建议1：参考文献栏是不是也可以做成zotero里已经存在的，加粗。来和其他的区分开。这样和关联文献中能够一致，只需要看一个栏目就心理有数了。

**Comment by MuiseDestiny** [comment]
**问题1**：小bug，会修复的。
**建议1**：已经有的，点击后可以跳转到本地所在条目，但是如果也需要的话，可以给他加上。
**问题2**：是readcube的API（源头api不知道是哪个，没调查过）。好几个网站推荐都是基于这个API，数量一般是5个。当然也有能推荐几十篇的API，但是我觉得太多了（有几个特别相关的就可以了）。
**建议1**：有考虑过，只是能做到这个功能的PDF只是部分，而且参考文献数量如果很多的话，逐一搜索本地会卡顿的。

综合考虑，我做成下图这样，只有鼠标停留出现浮窗时候才会搜索本地，这里的`Zotero`点击后可以跳转到Zotero对应的本地条目。

![image](https://user-images.githubusercontent.com/51939531/212289684-850384ca-bb1c-4ed7-8537-966cb6a49e7d.png)

不过如果能接收这个卡顿的话，是可以实现关联文献和参考文献统一突出显示本地文献的。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/212537553-1b4f0e22-e03b-42c9-9a2e-e949adbe4546.png)

**Comment by MuiseDestiny** [comment]
> 参考文献栏是不是也可以做成zotero里已经存在的，加粗。来和其他的区分开。这样和关联文献中能够一致，只需要看一个栏目就心理有数了。

已计划
