### ISSUE TITLE
安装插件产生的Addon Item条目疑问

### ISSUE THREAD

**Issue by GitYangym** [MuiseDestiny/zotero-reference#43]
作者您好，这是发现的一个小bug，只要打开pdf读文献就会在文库里会自动添加一个名为“Addon item”的条目，删除后时不时又会自动添加。我也不确定是不是您的插件导致的，仅仅是猜测，因为当我把您的插件移除以后就没有出现这个问题了，并且好友也出现了这个问题，所以应该不是个例。如果我的猜测有误，向您诚挚表达歉意。提前祝您新年快乐！
祝好，敬上！
![64c69b88d1747045b73006aca6a921d](https://user-images.githubusercontent.com/63669084/212551700-236d2cd7-9d81-4bae-aac0-f1ef97f1ff4e.jpg)

**Comment by MuiseDestiny** [comment]
用于同步阅读数据啊！不要删除，不然阅读数据都没了

**Comment by MuiseDestiny** [comment]
是这样的，最初阅读进度数据存本地，不能同步，有同学想要同步，就放笔记里了。然后新版本，我放其他字段里了，但是有同学不想放这里，还是想放笔记，所以又放笔记了。这个笔记是可以无限制同步，不占用300m空间的。

**Comment by GitYangym** [comment]
> 是这样的，最初阅读进度数据存本地，不能同步，有同学想要同步，就放笔记里了。然后新版本，我放其他字段里了，但是有同学不想放这里，还是想放笔记，所以又放笔记了。这个笔记是可以无限制同步，不占用300m空间的。

原来是这样啊，谢谢您的回复。但是reference插件我好像没有看到有阅读进度数据的功能😳

**Comment by MuiseDestiny** [comment]
> > 是这样的，最初阅读进度数据存本地，不能同步，有同学想要同步，就放笔记里了。然后新版本，我放其他字段里了，但是有同学不想放这里，还是想放笔记，所以又放笔记了。这个笔记是可以无限制同步，不占用300m空间的。
> 
> 原来是这样啊，谢谢您的回复。但是reference插件我好像没有看到有阅读进度数据的功能😳

看错了，以为是style下的回复，它会储存reference插件解析出来的参考文献。可以同步。

**Comment by GitYangym** [comment]
> > > 是这样的，最初阅读进度数据存本地，不能同步，有同学想要同步，就放笔记里了。然后新版本，我放其他字段里了，但是有同学不想放这里，还是想放笔记，所以又放笔记了。这个笔记是可以无限制同步，不占用300m空间的。
> > 
> > 
> > 原来是这样啊，谢谢您的回复。但是reference插件我好像没有看到有阅读进度数据的功能😳
> 
> 看错了，以为是style下的回复，它会储存reference插件解析出来的参考文献。可以同步。

如果关闭存储选项的话，能不能让他不自动添加“Addon item”条目了😂，感觉有点碍眼，哈哈，有点强迫症。

**Comment by MuiseDestiny** [comment]
一般看不到它吧，你说的碍眼是在哪里碍眼。方便的话截个图，我想想办法。

**Comment by Z0o0o** [comment]
> 一般看不到它吧，你说的碍眼是在哪里碍眼。方便的话截个图，我想想办法。

这个addon item和style产生的笔记是像之前一样可以都放到回收站里么，设置成强制无法删除

**Comment by MuiseDestiny** [comment]
> 这个addon item和style产生的笔记是像之前一样可以都放到回收站里么，设置成强制无法删除

有很大风险，我自己的数据就是被我清空回收站清空没了的。虽然可以拦截，但是随着Zotero升级，不能确保数据安全。

**Comment by MuiseDestiny** [comment]
任何有关数据储存的建议可以反馈至此。

目前策略：未分类目录下新建一个`Addon Item`条目，下面的笔记储存着文献库里一篇文献所有的数据，包括参考文献列表，阅读时间等等。

**Comment by GitYangym** [comment]
> 一般看不到它吧，你说的碍眼是在哪里碍眼。方便的话截个图，我想想办法。

嗯嗯，就是感觉对于reference插件来说，也没有什么需要同步的东西吧，感觉Addon item没啥用，但是又存放在文库里删不掉。大部分操作逻辑还是点开pdf再点下刷新就可以看参考文献了，也不太明白给他存储到本地笔记的意义是啥，笔记里也是代码组成的，也无法直接复制出来现成的文献表。仅仅是建议哦，因为我也不用style插件，仅仅从reference插件的角度看这个感觉作用不太大，还是最初的几个版本更干净一点，感觉不会污染文献库🤣🤣。谢谢作者！新年快乐！

**Comment by MuiseDestiny** [comment]
首选项关闭储存，然后删除addon item就可以了，储存是为了修改后保存修改的数据. 新年快乐~

**Comment by oneqiufeng** [comment]
就是说这个addon item是存储阅读进度的数据，想要保存阅读进度数据的话就不要删除嘛？我倒不觉得碍眼平时在分类条目里面也看不到，希望可以和作者一起想办法优化一下吧（说实话也就是一个设置附件的问题，我觉得可以增加到PDF的信息里面，修改一段代码信息放到PDF附件信息里就可以了，比如笔记或者PDF本身的数据里，不占用存储空间，也不会影响用户隐私）个人拙见望指点！谢谢！

**Comment by MuiseDestiny** [comment]
> 就是说这个addon item是存储阅读进度的数据，想要保存阅读进度数据的话就不要删除嘛？我倒不觉得碍眼平时在分类条目里面也看不到，希望可以和作者一起想办法优化一下吧（说实话也就是一个设置附件的问题，我觉得可以增加到PDF的信息里面，修改一段代码信息放到PDF附件信息里就可以了，比如笔记或者PDF本身的数据里，不占用存储空间，也不会影响用户隐私）个人拙见望指点！谢谢！

本身可以存成一个json的，首选项可以选择。这个json可以放在你的ondrive可同步目录下就可以实现同步。比存笔记好得多，推荐使用。

**Comment by ahhuipt** [comment]
![image](https://github.com/MuiseDestiny/zotero-reference/assets/130829182/805d1d0d-53ea-42b4-80f8-5909b0376885)
![image](https://github.com/MuiseDestiny/zotero-reference/assets/130829182/3e21f796-ff4d-4a9e-af9f-9f13aa56a353)
你好，我装了style插件，两个电脑同步出现两个Addon Item，每个Addon Item文件夹里还有相同的条目，这是咋回事，我同时也设置过json，可以只用json删掉Addon Item吗
