### ISSUE TITLE
使用google scholar api

### ISSUE THREAD

**Issue by he-hai** [MuiseDestiny/zotero-reference#44]
您好，感谢开发这个非常实用的的工具。  
可能是由于我不在国内的原因，默认来自readpaper的参考文献的浮窗文献信息很久不能加载下来。不知google scholar是否有api可用，能否加入这个功能。能显示标题、摘要（作者）即可。PubeMed可能也行，不过搜索能力可能没有google scholar好。谢谢。

**Comment by MuiseDestiny** [comment]
我有空研究研究~

**Comment by Haz1y** [comment]
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/50012377/212688186-14636f07-6ae6-4654-ad75-b52888491655.png">
想问下 为啥湖北移动的网络 无法j加载readpaper的api？ 挂梯子和不挂都是三个点

**Comment by Haz1y** [comment]
> 我有空研究研究~

想问下为何 湖北移动的网络 无法加载readpaper的api？起初怀疑是开了梯子，但是关了梯子还是一样
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/50012377/212688523-3fc126a1-f083-4b2d-bf9e-999e863f830e.png">

**Comment by Haz1y** [comment]
也尝试了 电信网络的手机热点，也还是这样 是为啥呢，还有有个功能是 无超链接的ref数字跳转，我记得这是之前style的功能吗？为何现在失效了呢？style用的2版本
<img width="613" alt="image" src="https://user-images.githubusercontent.com/50012377/212689502-65cac8bb-8584-4f9e-9de8-be0fee7cf157.png">

**Comment by MuiseDestiny** [comment]
> 也尝试了 电信网络的手机热点，也还是这样 是为啥呢，还有有个功能是 无超链接的ref数字跳转，我记得这是之前style的功能吗？为何现在失效了呢？style用的2版本 <img alt="image" width="613" src="https://user-images.githubusercontent.com/50012377/212689502-65cac8bb-8584-4f9e-9de8-be0fee7cf157.png">

无超链接，都不能跳转。

网络问题试试直接访问readpaper能否访问呢。

**Comment by Haz1y** [comment]
> > 也尝试了 电信网络的手机热点，也还是这样 是为啥呢，还有有个功能是 无超链接的ref数字跳转，我记得这是之前style的功能吗？为何现在失效了呢？style用的2版本 <img alt="image" width="613" src="https://user-images.githubusercontent.com/50012377/212689502-65cac8bb-8584-4f9e-9de8-be0fee7cf157.png">
> 
> 无超链接，都不能跳转。
> 
> 网络问题试试直接访问readpaper能否访问呢。

![image](https://user-images.githubusercontent.com/50012377/212697918-a6406020-7de9-47e1-a6c7-fa9c9eb03756.png)
是这个网站吗？可以访问 也可以按照题目检索到文章

**Comment by MuiseDestiny** [comment]
是所有文章readpaper的浮窗都不可以用嘛，个别的话发一下pdf。

**Comment by Haz1y** [comment]
> 是所有文章readpaper的浮窗都不可以用嘛，个别的话发一下pdf。

我这里是几个文献 找到的对应的ref都貌似不能访问，都是加载的红点，难道是不支持医学 生命科学领域的文章吗？
[Uploading Liu et al. - 2022 - Integrated multi-omics profiling yields a clinical.pdf…]()
![image](https://user-images.githubusercontent.com/50012377/212702704-32914651-7926-43ee-b1dc-210e6399e915.png)

**Comment by MuiseDestiny** [comment]
> > 是所有文章readpaper的浮窗都不可以用嘛，个别的话发一下pdf。
> 
> 我这里是几个文献 找到的对应的ref都貌似不能访问，都是加载的红点，难道是不支持医学 生命科学领域的文章吗？ Uploading Liu et al. - 2022 - Integrated multi-omics profiling yields a clinical.pdf… ![image](https://user-images.githubusercontent.com/50012377/212702704-32914651-7926-43ee-b1dc-210e6399e915.png)

PDF没上传好

**Comment by he-hai** [comment]
> > > 是所有文章readpaper的浮窗都不可以用嘛，个别的话发一下pdf。
> > 
> > 
> > 我这里是几个文献 找到的对应的ref都貌似不能访问，都是加载的红点，难道是不支持医学 生命科学领域的文章吗？ Uploading Liu et al. - 2022 - Integrated multi-omics profiling yields a clinical.pdf… ![image](https://user-images.githubusercontent.com/50012377/212702704-32914651-7926-43ee-b1dc-210e6399e915.png)
> 
> PDF没上传好

等下。上传PDF是什么意思？插件会把本地pdf文件上传吗？

**Comment by MuiseDestiny** [comment]
> > > > 是所有文章readpaper的浮窗都不可以用嘛，个别的话发一下pdf。
> > > 
> > > 
> > > 我这里是几个文献 找到的对应的ref都貌似不能访问，都是加载的红点，难道是不支持医学 生命科学领域的文章吗？ Uploading Liu et al. - 2022 - Integrated multi-omics profiling yields a clinical.pdf… ![image](https://user-images.githubusercontent.com/50012377/212702704-32914651-7926-43ee-b1dc-210e6399e915.png)
> > 
> > 
> > PDF没上传好
> 
> 等下。上传PDF是什么意思？插件会把本地pdf文件上传吗？

你刚刚发的pdf我下载不了。

**Comment by MuiseDestiny** [comment]
> > > > 是所有文章readpaper的浮窗都不可以用嘛，个别的话发一下pdf。
> > > 
> > > 
> > > 我这里是几个文献 找到的对应的ref都貌似不能访问，都是加载的红点，难道是不支持医学 生命科学领域的文章吗？ Uploading Liu et al. - 2022 - Integrated multi-omics profiling yields a clinical.pdf… ![image](https://user-images.githubusercontent.com/50012377/212702704-32914651-7926-43ee-b1dc-210e6399e915.png)
> > 
> > 
> > PDF没上传好
> 
> 等下。上传PDF是什么意思？插件会把本地pdf文件上传吗？

插件不会上传用户数据，开源，绝对安全。

**Comment by Haz1y** [comment]
> > > > > 是所有文章readpaper的浮窗都不可以用嘛，个别的话发一下pdf。
> > > > 
> > > > 
> > > > 我这里是几个文献 找到的对应的ref都貌似不能访问，都是加载的红点，难道是不支持医学 生命科学领域的文章吗？ Uploading Liu et al. - 2022 - Integrated multi-omics profiling yields a clinical.pdf… ![image](https://user-images.githubusercontent.com/50012377/212702704-32914651-7926-43ee-b1dc-210e6399e915.png)
> > > 
> > > 
> > > PDF没上传好
> > 
> > 
> > 等下。上传PDF是什么意思？插件会把本地pdf文件上传吗？
> 
> 你刚刚发的pdf我下载不了。

已重新上传
[Liu et al. - 2022 - Integrated multi-omics profiling yields a clinical.pdf](https://github.com/MuiseDestiny/zotero-reference/files/10426775/Liu.et.al.-.2022.-.Integrated.multi-omics.profiling.yields.a.clinical.pdf)

**Comment by he-hai** [comment]
哦，误会了。不好意思。
我这边是所有这两天点开的文献都加载不了refence信息

**Comment by MuiseDestiny** [comment]
> 哦，误会了。不好意思。 我这边是所有这两天点开的文献都加载不了refence信息

![image](https://user-images.githubusercontent.com/51939531/212706698-656316c6-fff7-4581-aa3d-8ac5799332fa.png)
试了下，可以的。不过好奇怪，我觉得这些API除了知网应该都是国内外通用的。

**Comment by Haz1y** [comment]
> > 哦，误会了。不好意思。 我这边是所有这两天点开的文献都加载不了refence信息
> 
> ![image](https://user-images.githubusercontent.com/51939531/212706698-656316c6-fff7-4581-aa3d-8ac5799332fa.png) 试了下，可以的。不过好奇怪，我觉得这些API除了知网应该都是国内外通用的。

我这里就是无法加载，好奇怪欸，我是国内 移动宽带/ 电信热点 + 全局梯子 都测试了，然后 网页也能访问，神奇的bug
![image](https://user-images.githubusercontent.com/50012377/212707573-e0b9b5c2-051b-444a-bfd7-018e1ed640d8.png)

**Comment by MuiseDestiny** [comment]
> > > 哦，误会了。不好意思。 我这边是所有这两天点开的文献都加载不了refence信息
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51939531/212706698-656316c6-fff7-4581-aa3d-8ac5799332fa.png) 试了下，可以的。不过好奇怪，我觉得这些API除了知网应该都是国内外通用的。
> 
> 我这里就是无法加载，好奇怪欸，我是国内 移动宽带/ 电信热点 + 全局梯子 都测试了，然后 网页也能访问，神奇的bug ![image](https://user-images.githubusercontent.com/50012377/212707573-e0b9b5c2-051b-444a-bfd7-018e1ed640d8.png)

![image](https://user-images.githubusercontent.com/51939531/212709448-b729cb06-9527-4d67-bbbb-b4aef1debee2.png)
这里圆点点一下。

**Comment by Haz1y** [comment]
> > > > 哦，误会了。不好意思。 我这边是所有这两天点开的文献都加载不了refence信息
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/51939531/212706698-656316c6-fff7-4581-aa3d-8ac5799332fa.png) 试了下，可以的。不过好奇怪，我觉得这些API除了知网应该都是国内外通用的。
> > 
> > 
> > 我这里就是无法加载，好奇怪欸，我是国内 移动宽带/ 电信热点 + 全局梯子 都测试了，然后 网页也能访问，神奇的bug ![image](https://user-images.githubusercontent.com/50012377/212707573-e0b9b5c2-051b-444a-bfd7-018e1ed640d8.png)
> 
> ![image](https://user-images.githubusercontent.com/51939531/212709448-b729cb06-9527-4d67-bbbb-b4aef1debee2.png) 这里圆点点一下。

解决了，是我傻了，原来可以切换页面，我以为是在加载，然后就是能获取ref的IF吗？easyScholar的api可以调度吗？ 然后还有关于stype的#标签，我个人是有这个需求，手动打上分类的标签，会很方便筛选，原本的emoji的信息量不够，不够精准

**Comment by MuiseDestiny** [comment]
> > > > > 哦，误会了。不好意思。 我这边是所有这两天点开的文献都加载不了refence信息
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/51939531/212706698-656316c6-fff7-4581-aa3d-8ac5799332fa.png) 试了下，可以的。不过好奇怪，我觉得这些API除了知网应该都是国内外通用的。
> > > 
> > > 
> > > 我这里就是无法加载，好奇怪欸，我是国内 移动宽带/ 电信热点 + 全局梯子 都测试了，然后 网页也能访问，神奇的bug ![image](https://user-images.githubusercontent.com/50012377/212707573-e0b9b5c2-051b-444a-bfd7-018e1ed640d8.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51939531/212709448-b729cb06-9527-4d67-bbbb-b4aef1debee2.png) 这里圆点点一下。
> 
> 解决了，是我傻了，原来可以切换页面，我以为是在加载，然后就是能获取ref的IF吗？easyScholar的api可以调度吗？ 然后还有关于stype的#标签，我个人是有这个需求，手动打上分类的标签，会很方便筛选，原本的emoji的信息量不够，不够精准

哈哈哈完全错乱了，style的建议在reference提。我的问题，只更新了插件，readme没更。

**Comment by he-hai** [comment]
哈哈，我也以为是在加载，我也可以用

**Comment by MuiseDestiny** [comment]
@Haz1y  影响因子可以加入。
