### ISSUE TITLE
如何关闭打开的分割窗口库（分栏）

### ISSUE THREAD

**Issue by luoyp32** [MuiseDestiny/zotero-reference#45]
点击跳转链接如Fig 4，会在分割界面（横向/竖向）跳转，主阅读界面无跳转。但是我想关掉分割界面却不知道在哪里关闭

**Comment by dyjcow** [comment]
我也有同样的疑问

**Comment by MuiseDestiny** [comment]
@dyjcow @luoyp32 
右键PDF，取消勾选横向分割。

**Comment by luoyp32** [comment]
感谢！就是有点不方便

**Comment by luoyp32** [comment]
> @dyjcow @luoyp32 右键PDF，取消勾选横向分割。

感谢！就是有点不方便

**Comment by MuiseDestiny** [comment]
以后有时间写一个提取表格图片插件，替代这个
