### ISSUE TITLE
crtl+点击实现跳转zotero条目而非网页链接

### ISSUE THREAD

**Issue by pencilheart** [MuiseDestiny/zotero-reference#46]
是否可实现`ctrl+点击`已存在的文献，跳转到zotero条目而非链接？

**Comment by MuiseDestiny** [comment]
> 是否可实现`ctrl+点击`已存在的文献，跳转到zotero条目而非链接？

浮窗内如有`Zotero`标签，跳转的是Zotero的条目，[这里](https://github.com/MuiseDestiny/zotero-reference/issues/42)与这个需求很相似，如果能接受卡顿，可以做的。

**Comment by pencilheart** [comment]
如果没理解错的话，这块功能应该主要是找文献嘛，那如果列表中有已关联的条目，跳转到zotero应该会更合理一些。卡顿的话应该可以接受吧，毕竟点击刷新时也是需要一点时间的。

**Comment by pencilheart** [comment]
现在还未实现此功能

**Comment by MuiseDestiny** [comment]
可以跳转，但不是ctrl 点击。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/222658984-9e49459a-21b8-4a68-96ef-2bf668eb8627.png)

**Comment by pencilheart** [comment]
这个按钮有点远感觉，有时瞄准过去，但是浮窗却消失了。。

**Comment by pencilheart** [comment]
前来感谢！最新版本此功能已实现！！撒花🎉
