### ISSUE TITLE
参考文献来源可以使用semanticscholar的API

### ISSUE THREAD

**Issue by mayq97** [MuiseDestiny/zotero-reference#5]
例如：
对于arxiv 的上论文 https://api.semanticscholar.org/graph/v1/paper/arXiv:2005.14165?fields=title,abstract,fieldsOfStudy,references,references.year,references.title,year

对于有doi的论文https://api.semanticscholar.org/graph/v1/paper/10.1038/s41586-020-2766-y?fields=title,abstract,fieldsOfStudy,references,references.year,references.title,year

**Comment by MuiseDestiny** [comment]
好的，感谢

**Comment by huzizhan** [comment]
跟进了解一下，使用semanticscholar api的话，有没有可能获取到citations的文献信息呢？即这篇文章在哪里被引用了～

**Comment by mayq97** [comment]
semanticscholar api 目前仅仅可以通过论文之间的引用关系，而不能提供具体的引用上下文信息
