### ISSUE TITLE
根据参考文献添加的建议

### ISSUE THREAD

**Issue by Mashmall** [MuiseDestiny/zotero-reference#50]
我有一个在多个文件夹上的文献，但是我感觉这篇文献的参考添加的时候会在每一个它存在的文件夹下添加这些文献，请问是否可以设置为只在该文件夹下添加相关的参考文献，同时添加会使一些归档的文件夹很乱，谢谢！

**Comment by MuiseDestiny** [comment]
> 我有一个在多个文件夹上的文献，但是我感觉这篇文献的参考添加的时候会在每一个它存在的文件夹下添加这些文献，请问是否可以设置为只在该文件夹下添加相关的参考文献，同时添加会使一些归档的文件夹很乱，谢谢！



> 我有一个在多个文件夹上的文献，但是我感觉这篇文献的参考添加的时候会在每一个它存在的文件夹下添加这些文献，请问是否可以设置为只在该文件夹下添加相关的参考文献，同时添加会使一些归档的文件夹很乱，谢谢！

可以的

**Comment by MuiseDestiny** [comment]
可以按ctrl点击+添加关联，就不会在每一个文件夹下出现了。

**Comment by Mashmall** [comment]
> 可以按ctrl点击+添加关联，就不会在每一个文件夹下出现了。

实现了 哇塞 太棒了 原来你早就实现了这个功能啊^v^
