### ISSUE TITLE
悬浮框无法在线匹配到论文的信息

### ISSUE THREAD

**Issue by bgbaizh** [MuiseDestiny/zotero-reference#52]
作者您好！我的插件版本是0.2.6；zotero版本是6.0.20. 不知道为什么我的悬浮框中无法出现在线匹配的信息。已经挂梯子了，梯子里也显示通过代理访问crossref。
<img width="998" alt="image" src="https://user-images.githubusercontent.com/118628082/216809676-d7c82bbb-310f-446a-825a-fb647afafd4b.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/118628082/216809808-d0bf5684-74fa-4bc1-9bb4-eb16327fb2fc.png">

**Comment by MuiseDestiny** [comment]
好多小点，点击一下有惊喜

**Comment by bgbaizh** [comment]
啊这2333，我以为那个是加载符号，谢谢啦!
