### ISSUE TITLE
安装后首选项中未出现设置界面

### ISSUE THREAD

**Issue by Zessi-C** [MuiseDestiny/zotero-reference#53]
![image](https://user-images.githubusercontent.com/68623660/217122337-e24f8dd5-256b-402a-abc4-f4bcfb0ac6fb.png)
安装0.2.7与0.2.6后首选项中均未出现该插件对应界面，但参考文献功能可正常使用

**Comment by MuiseDestiny** [comment]
偶尔会失败，重启zo，以及电脑试试呢

**Comment by Zessi-C** [comment]
感谢，但重启zo、电脑后均仍未出现

**Comment by MuiseDestiny** [comment]
> 感谢，但重启zo、电脑后均仍未出现

好的，我偶尔也会出现这种情况，等下次出现我看下原因。

在此之前，你可以通过下面的方式进行一些设置。
![image](https://user-images.githubusercontent.com/51939531/217128675-1366a101-e357-4eea-8d1e-7a26dd1e551c.png)

**Comment by Zessi-C** [comment]
非常感谢！

**Comment by MuiseDestiny** [comment]
我迁移到最新模板了，可以试试可以不。

**Comment by Zessi-C** [comment]
依然不稳定，有的时候依然不出现，有的时候出现两个
![image](https://user-images.githubusercontent.com/68623660/219290393-8cb767dc-31d8-4d0c-96b2-8a5fbee232f8.png)

**Comment by MuiseDestiny** [comment]
它很极端哈哈哈
