### ISSUE TITLE
侧边栏文献条目无法加载文献信息

### ISSUE THREAD

**Issue by LuisWangYubin** [MuiseDestiny/zotero-reference#54]
![微信图片_20230207165313](https://user-images.githubusercontent.com/108571560/217197421-598b756c-c408-4f47-92aa-1f2d13c53e7a.jpg)

6.0.20版本的zotero，0.2.6版本的插件，侧边栏文献条目加载不出来文献信息，ctrl+单击也没法跳转到文献网页

**Comment by MuiseDestiny** [comment]
小圆点，点击一下

**Comment by LuisWangYubin** [comment]
奥奥，好了，但是ctrl+单击的话右下方只显示[pending] request URL from API，无法跳转

**Comment by MuiseDestiny** [comment]
> 奥奥，好了，但是ctrl+单击的话右下方只显示[pending] request URL from API，无法跳转

不是立刻跳转的，对于PDF里没有超链接的（下图是有的）需要根据标题查询DOI再跳转
![image](https://user-images.githubusercontent.com/51939531/217709059-24b58ba8-f266-4aea-81e8-48deeacc6a0e.png)

**Comment by LuisWangYubin** [comment]
明白了，谢谢！
