### ISSUE TITLE
0.3.0版本不能正常使用

### ISSUE THREAD

**Issue by GFDGIT** [MuiseDestiny/zotero-reference#56]
侧边栏无显示，报错如下：

[JavaScript Error: "[Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setIntPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js :: pref :: line 143"  data: no]"]
pref@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js:143:11
@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/prefs.js:10:1
setDefaultPrefs@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js:151:3
startup@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///D:/Software/Zotero/Data/Mozilla/Profile/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js:85:5

version => 6.0.22-beta.1+34bb51f58, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => zh-CN, appName => Zotero, appVersion => 6.0.22-beta.1+34bb51f58, extensions => Folder Import for Zotero (0.0.5, extension), Zotero PDF Preview (0.3.7, extension), Background for Zotero Pdf Reader (0.0.2, extension), Zotero Tag (0.3.0, extension), Chartero (1.3.2, extension), Jasminum (0.2.4, extension), Zotero Better Notes (0.8.8, extension), Tara (0.0.1, extension), Zotero LibreOffice Integration (6.0.4.SA.6.0.22-beta.1+34bb51f58, extension), Zotero Word for Windows Integration (6.0.2.SA.6.0.22-beta.1+34bb51f58, extension), Zotero Citation (0.0.7, extension), Zotero PDF Translate (1.0.5, extension), Zotero Style (2.1.1, extension), Zotero Reference (0.3.0, extension)

**Comment by MuiseDestiny** [comment]
把prefs.js有关zoteroreference删除
![image](https://user-images.githubusercontent.com/51939531/217747720-e7deff9c-fc04-43b4-a709-4e5a1d1cf7f0.png)

**Comment by GFDGIT** [comment]
删除，重启后正常了
