### ISSUE TITLE
右边没有参考文献

### ISSUE THREAD

**Issue by pweni** [MuiseDestiny/zotero-reference#57]
zotero 为最新版 6.0.20
zotero-reference 也是最新版，后面降了插件一个版本还是没有
![image](https://user-images.githubusercontent.com/25874023/217902467-7fa919f0-63be-4997-a7d2-d33b3b00e55d.png)
是我的操作有什么问题吗?（大哭）

**Comment by MuiseDestiny** [comment]
打开pdf后侧边栏

**Comment by r0loper** [comment]
> 打开pdf后侧边

请问这个打开pdf后侧边栏是啥意思啊，还有其他的侧边栏吗，我在macos也遇到了相同的问题

**Comment by r0loper** [comment]
> > 打开pdf后侧边
> 
> 请问这个打开pdf后侧边栏是啥意思啊，还有其他的侧边栏吗，我在macos也遇到了相同的问题

突然发现是我断句没断对，意思就是双击打开pdf阅读界面后的侧边栏看有没有参考文献，不过我这个macos下还是没有啊，zotero是最新6.0.21，插件版本是最新可下载的那个
<img width="581" alt="截屏2023-02-10 上午9 28 31" src="https://user-images.githubusercontent.com/70384699/217977562-7df7e645-877a-4901-8299-c2e0dbcdb0ce.png">

**Comment by MuiseDestiny** [comment]
> > > 打开pdf后侧边
> > 
> > 
> > 请问这个打开pdf后侧边栏是啥意思啊，还有其他的侧边栏吗，我在macos也遇到了相同的问题
> 
> 突然发现是我断句没断对，意思就是双击打开pdf阅读界面后的侧边栏看有没有参考文献，不过我这个macos下还是没有啊，zotero是最新6.0.21，插件版本是最新可下载的那个 <img alt="截屏2023-02-10 上午9 28 31" width="581" src="https://user-images.githubusercontent.com/70384699/217977562-7df7e645-877a-4901-8299-c2e0dbcdb0ce.png">

以前可以用吗，新版本有一个bug

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-reference/issues/56
可以参考这个

**Comment by r0loper** [comment]
> > > > 打开pdf后侧边
> > > 
> > > 
> > > 请问这个打开pdf后侧边栏是啥意思啊，还有其他的侧边栏吗，我在macos也遇到了相同的问题
> > 
> > 
> > 突然发现是我断句没断对，意思就是双击打开pdf阅读界面后的侧边栏看有没有参考文献，不过我这个macos下还是没有啊，zotero是最新6.0.21，插件版本是最新可下载的那个 <img alt="截屏2023-02-10 上午9 28 31" width="581" src="https://user-images.githubusercontent.com/70384699/217977562-7df7e645-877a-4901-8299-c2e0dbcdb0ce.png">
> 
> 以前可以用吗，新版本有一个bug

我是昨天才知道这个插件的，第一次使用

**Comment by MuiseDestiny** [comment]
那试试0.3.0之前的版本呢

**Comment by r0loper** [comment]
> #56 可以参考这个

请问#56这个回答里面提到的名为“prefs.js”的文件在哪可以找到啊，我在mac上搜索了一下好像没有这个文件

**Comment by r0loper** [comment]
> 那试试0.3.0之前的版本呢



> 那试试0.3.0之前的版本呢

我尝试了插件0.3.0之前的版本后发现好使了，十分感谢

**Comment by MuiseDestiny** [comment]
> > 那试试0.3.0之前的版本呢
> 
> > 那试试0.3.0之前的版本呢
> 
> 我尝试了插件0.3.0之前的版本后发现好使了，十分感谢

等我修复再装0.3.0之后的吧

**Comment by r0loper** [comment]
> > > 那试试0.3.0之前的版本呢
> > 
> > 
> > > 那试试0.3.0之前的版本呢
> > 
> > 
> > 我尝试了插件0.3.0之前的版本后发现好使了，十分感谢
> 
> 等我修复再装0.3.0之后的吧

好的，十分感谢

**Comment by pweni** [comment]
> 打开pdf后侧边栏

 安装了0.2.7版本的可以用了,0.3.0及其以上都用不了（zotero verion==6.0.20)

**Comment by MuiseDestiny** [comment]
> > 打开pdf后侧边栏
> 
> 安装了0.2.7版本的可以用了,0.3.0及其以上都用不了（zotero verion==6.0.20)

能安装最新版，给我看看报错吗
`帮助`->`调试日志`->`查看输出日志`，顶部有报错

**Comment by huangzhenhao90** [comment]
> > > 打开pdf后侧边栏
> > 
> > 
> > 安装了0.2.7版本的可以用了,0.3.0及其以上都用不了（zotero verion==6.0.20)
> 
> 能安装最新版，给我看看报错吗 `帮助`->`调试日志`->`查看输出日志`，顶部有报错


[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: undefined entity
Location: jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml
Line Number 3, Column 5:" {file: "jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/preferences.xhtml" line: 3 column: 5 source: "    <caption label="&zotero.zoteroreference.caption.refresh;" />"}]

[JavaScript Error: "Error: Target container is not a DOM element." {file: "resource://zotero/loader.jsm -> resource://zotero/react-dom.js" line: 26121}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblinput@chrome://zotero/content/bindings/preferences-mac.xml:1328:9


[JavaScript Error: "TypeError: preference is null" {file: "chrome://zotero/content/bindings/preferences-mac.xml" line: 1277}]
userChangedValue@chrome://zotero/content/bindings/preferences-mac.xml:1277:19
onxblchange@chrome://zotero/content/bindings/preferences-mac.xml:1323:9


[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "TypeError: tabs.querySelectorAll(...)[options.targetIndex] is undefined" {file: "resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/bootstrap.js -> jar:file:///Users/zhenhao/Library/Application%20Support/Zotero/Profiles/gj8tlf5p.default/extensions/zoteroreference@polygon.org.xpi!/chrome/content/scripts/index.js" line: 2490}]

[JavaScript Error: "Error processing feed from https://academic.oup.com/rss/site_5397/3258.xml:

Error: No Feed"]

[JavaScript Error: "Error processing feed from https://academic.oup.com/rss/site_5397/3258.xml:

Error: No Feed"]

[JavaScript Error: "Error processing feed from https://academic.oup.com/rss/site_5397/3258.xml:

Error: No Feed"]

version => 6.0.20, platform => MacIntel, oscpu => Intel Mac OS X 10.16, locale => zh-CN, appName => Zotero, appVersion => 6.0.20, extensions => Zotero Reference (0.3.1, extension), Zotero Word for Mac Integration (6.0.4.SA.6.0.20, extension), Zotero LibreOffice Integration (6.0.3.SA.6.0.20, extension), Shockwave Flash (34.0.0.277, plugin)

**Comment by MuiseDestiny** [comment]
为什么你的截图没有`关联文献`

![image](https://user-images.githubusercontent.com/51939531/218287489-f1242d23-b7a5-4cac-a632-e58d65054e5e.png)

错误原因是插件会把`参考文献`插入到`关联文献`后，但你的截图没有`关联文献`所以报错

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.3.2

**Comment by 0121k** [comment]
![){UTK8X}M2$IGI T3P(ETF3](https://user-images.githubusercontent.com/122724785/218308323-273bd906-445a-4307-b321-8fa0094ca2a9.png)

**Comment by MuiseDestiny** [comment]
> ![){UTK8X}M2$IGI T3P(ETF3](https://user-images.githubusercontent.com/122724785/218308323-273bd906-445a-4307-b321-8fa0094ca2a9.png)

长按刷新，强制刷新试试

**Comment by 0121k** [comment]
参考列表文献，在多次打开此pdf阅读后，列表再也无法显示（刷新和更新插件同样无法解决），另外直接“ctrl+”添加文献出现抓取错误目标，只能通过DOI点开网站进行手动抓取，0.1.9版本可以直接抓取。拜托拜托~

**Comment by MuiseDestiny** [comment]
> 参考列表文献，在多次打开此pdf阅读后，列表再也无法显示（刷新和更新插件同样无法解决），另外直接“ctrl+”添加文献出现抓取错误目标，只能通过DOI点开网站进行手动抓取，0.1.9版本可以直接抓取。拜托拜托~

具体点
