### ISSUE TITLE
有没有可能实现悬浮在超链接上显示对应的参考文献信息

### ISSUE THREAD

**Issue by cesaryuan** [MuiseDestiny/zotero-reference#59]
首先感谢大佬提供的好用的插件😁，想问下有没有可能实现悬浮在引用超链接上（或者右键点击引用超链接）显示对应的参考文献信息，如下图所示：

![image](https://user-images.githubusercontent.com/35998162/218682167-e65287a6-e699-4fe6-9114-779f8abe0dba.png)

现在想要查看某个引用超链接对应的参考文献信息，需要记住他的序号，然后在右边的参考文献列表中找到这个序号，然后悬浮等待参考文献信息出现😂，如果能实现上面的功能就非常好啦。

我看了下好像能访问到 PDFViewerApplication 对象，不知道能不能在这上面做文章

**Comment by MuiseDestiny** [comment]
可以实现的，readpaper就是这样的。

**Comment by 754932057** [comment]
> 可以实现的，readpaper就是这样的。

请问现在实现了没啊，大佬在文章中悬停就能看到引用的文献

**Comment by MuiseDestiny** [comment]
> 首先感谢大佬提供的好用的插件😁，想问下有没有可能实现悬浮在引用超链接上（或者右键点击引用超链接）显示对应的参考文献信息，如下图所示：

![image](https://user-images.githubusercontent.com/51939531/222646034-24477b0d-670a-4aa6-83e3-3a8e6c24923d.png)

预览版，这样子，匹配这些信息太难实现了（容易误判漏判），需要手动选区一下。
