### ISSUE TITLE
中文参考文献有双列排布的匹配有些许问题？

### ISSUE THREAD

**Issue by SmallerTiny** [MuiseDestiny/zotero-reference#60]
如题，如果文献是双列排布的话，似乎只能够识别到左边的一列，这样是我设置问题吗，还是可以解决的？请大佬了解一下

**Comment by MuiseDestiny** [comment]
> 如题，如果文献是双列排布的话，似乎只能够识别到左边的一列，这样是我设置问题吗，还是可以解决的？请大佬了解一下

可以识别三列多列，发一下pdf

**Comment by SmallerTiny** [comment]
(https://panandbox.myDS.me:5001/d/s/sOcmV9Uc9MexOCKvvo2IOXbkdFJSoibG/py5W73MiWyOX80JHZ3r3Jwcb33Kq8obL-zLsg6TMlOAo)
不好意思GitHub用得少，搞不清邮箱，弄个文件链接您看一下

**Comment by SmallerTiny** [comment]
> 

这个文献我这里只识别到了前十个

**Comment by MuiseDestiny** [comment]
可以识别多列
![image](https://user-images.githubusercontent.com/51939531/219236219-92a66190-13ce-40ab-a41c-2db88cc43031.png)

你发的pdf，readpaper只识别到8个
![image](https://user-images.githubusercontent.com/51939531/219242070-3bebb5cd-5716-4b92-93ae-ec7813f2b969.png)


总结，PDF不够规范
具体表现就是，字体大小不一致。如果适配这种不规范的PDF可能会对规范的PDF造成错误影响。所以见谅。
![image](https://user-images.githubusercontent.com/51939531/219243291-d876acea-3e4c-41c2-8860-1cfbb93608da.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/219243643-708d7ee4-3cc3-4ecf-8122-e6dd0ba5e576.png)

假设它的字体大小规范，上图可以看出来插件具备识别多列的能力

**Comment by SmallerTiny** [comment]
非常感谢您的耐心解答
