### ISSUE TITLE
打开某一个pdf，参考文献还是不会自动刷新，必须手动点击刷新，设置里已经打开自动刷新开关了

### ISSUE THREAD

**Issue by heyeruoqi** [MuiseDestiny/zotero-reference#61]
打开某一个pdf，参考文献还是不会自动刷新，必须手动点击刷新，设置里已经打开自动刷新开关了

**Comment by MuiseDestiny** [comment]
> 打开某一个pdf，参考文献还是不会自动刷新，必须手动点击刷新，设置里已经打开自动刷新开关了

最新版修复了，你安装的可能是老版本，下载最新版试试。
![image](https://user-images.githubusercontent.com/51939531/219597836-ace805cc-88ce-4f74-86c9-80ccb5632fc5.png)
