### ISSUE TITLE
参考文献功能不显示

### ISSUE THREAD

**Issue by xiaooomd** [MuiseDestiny/zotero-reference#62]
只添加reference插件时，右侧栏有参考文献功能，但是加载其余的插件并重启后，只有翻译功能

**Comment by MuiseDestiny** [comment]
> 只添加reference插件时，右侧栏有参考文献功能，但是加载其余的插件并重启后，只有翻译功能

翻译插件版本号多少，我测试下

**Comment by xiaooomd** [comment]
zotero—reference是 0.3.4，最近的这一版，zotero-pdf-translate是1.0.9，麻烦了

**Comment by MuiseDestiny** [comment]
重新下载ref插件最新版安装重启试试。如果还不行

打开一个pdf，并打开下图
![image](https://user-images.githubusercontent.com/51939531/219952973-27473115-267f-49b3-b5a0-c8c439e9ce57.png)

查看输出日志，截图下开头
![image](https://user-images.githubusercontent.com/51939531/219952997-91a6e6d7-e28a-4804-a82c-a5435ef1fbb3.png)

**Comment by xiaooomd** [comment]
![reference_bug](https://user-images.githubusercontent.com/51357799/219953632-87885920-d5a6-45d5-8c02-ecb0589c4e6a.png)
你好，这个是现在的输出日志

**Comment by xiaooomd** [comment]
这个是我删除ref插件，然后重启软件，安装ref插件的日志
![reference_bug2](https://user-images.githubusercontent.com/51357799/219953934-e02c1491-cfd3-40e2-86b3-40105d3fd07a.png)

**Comment by MuiseDestiny** [comment]
稍等，我修复下

**Comment by MuiseDestiny** [comment]
一会帮忙测试下

**Comment by xiaooomd** [comment]
这个是我重新安装插件以后，再次重启的日志，大晚上的打扰了，麻烦了，谢谢！！！
![reference_bug3](https://user-images.githubusercontent.com/51357799/219954017-584ea863-f422-4898-b287-17f13cff53b4.png)

**Comment by xiaooomd** [comment]
> 一会帮忙测试下
真的太感谢了！

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.3.5

**Comment by MuiseDestiny** [comment]
测试以下试试

**Comment by xiaooomd** [comment]
好的谢谢

**Comment by xiaooomd** [comment]
> 测试以下试试
你好，我测试了一下，现在能显示了！十分感谢！！！

**Comment by MuiseDestiny** [comment]
> > 测试以下试试
> > 你好，我测试了一下，现在能显示了！十分感谢！！！

好的
