### ISSUE TITLE
有没有可能跟原有的侧边栏关联文献对接？

### ISSUE THREAD

**Issue by Rsweater** [MuiseDestiny/zotero-reference#63]
关键文献这个，在zotero-style里面的关系图谱用到了，就是借鉴obsidian那种引用的关系图谱，感觉挺好。还有那个Chartero也用到了，感觉这两个跟zotero-reference配合起来挺好用。

**Comment by MuiseDestiny** [comment]
详细说说，复杂的话画个草图。

**Comment by Rsweater** [comment]
> 详细说说，复杂的话画个草图。

就是这个地方，如果这个手动添加的可以用zotero-reference的方式添加的话，那就方便了。
可以将参考文献放里面，然后搞个新的相关文献还是什么的放原来的关联文献。或者其他的什么方式
![2023-02-21 13 28 35](https://user-images.githubusercontent.com/49091147/220256911-efcaa2a9-dc43-4cac-bc2d-fc1be2a5737b.png)
![2023-02-21 13 36 12](https://user-images.githubusercontent.com/49091147/220256914-b35dce52-b357-41f5-bbe1-d53b1967ef6d.png)

**Comment by MuiseDestiny** [comment]
暂时不对接，功能为主，不做太花哨功能。花哨的可以在style里提。
