### ISSUE TITLE
参考文献的抓取全部错误，添加进我的文库的条目和参考文献条目完全不同

### ISSUE THREAD

**Issue by lllaterOn** [MuiseDestiny/zotero-reference#64]
首选项设置为优先从pdf读取参考文献（设置为从api读取总是失败），在面板内显示的参考文献是正确的，点击加号添加进我的文库的文献是完全其他的文献。检查浮窗内参考文献的源，发现抓取的信息完全是另一篇文献的信息。如下图所示，不知道能否修复？我的想法是中文的参考文献直接在知网内搜索文献名字就可以抓取条目信息了，英文文献再使用crossref这样的源。
<img width="1524" alt="Snipaste_2023-02-21_09-05-45" src="https://user-images.githubusercontent.com/78646625/220222951-8eea3a3b-f837-4f76-a921-b86f90114b72.png">

**Comment by lllaterOn** [comment]
补充信息：我已经安装了茉莉花插件，我看项目说明里面说已经支持了知网，但参考文献中的中文文献还是用crossref这类源搜索信息的。此外我还安装了sci-hub插件，不知道是否因为这个原因冲突？

**Comment by MuiseDestiny** [comment]
中文原本支持从知网抓的，但是指望本身参考文献信息不全，所以后来我去除了。知网文献（或者说大多数中文PDF）是没有API获取参考文献功能的。

抓取错误可以把这个PDF发给我。

面板正确是因为从PDF获取的，抓取错误是因为利用PDF获取的文献信息去知网搜索错误搜索成了其它文献，可以长按某个文献，编辑它仅剩下一个作者+标题的形式成功率比较高。总之知网是块硬骨头，很难适配。

**Comment by MuiseDestiny** [comment]
对于悬浮窗，我设置了条件，中文占据一定百分比时候才会调用知网搜索文献信息。或许这个阈值可以调整下，这么设置是为了防止对知网请求过多。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/220228459-1418c410-0899-4304-bc61-65c63a9939c1.png)

比如，改成这样，正确率会提升。

**Comment by lllaterOn** [comment]
好的，明白了。我的想法参考文献里面的条目可以通过PDF本身获取，之后通过加号可以直接在知网内搜索文献的中文名（对于中文文献，可能大部分文献的中文名都是在头两个英文句号中间的那一段文字），之后抓取正确的条目信息到文库内。还有个小小的问题就是，通过pdf抓取的参考文献信息内有大量的空格，不知道能不能把这些空格去掉。

**Comment by MuiseDestiny** [comment]
> 内有大量的空格、

可以去除。

> 我的想法参考文献里面的条目可以通过PDF本身获取，之后通过加号可以直接在知网内搜索文献的中文名（对于中文文献，可能大部分文献的中文名都是在头两个英文句号中间的那一段文字），之后抓取正确的条目信息到文库内。

现在运行是这个逻辑，只是从这一对文字很难匹配到作者和标题。所以需要手动精简以下，英文文献相对好匹配一些。

**Comment by lllaterOn** [comment]
了解了，期待插件越来越完美，感谢作者！

**Comment by zhbery** [comment]
> 中文原本支持从知网抓的，但是指望本身参考文献信息不全，所以后来我去除了。知网文献（或者说大多数中文PDF）是没有API获取参考文献功能的。
> 
> 抓取错误可以把这个PDF发给我。
> 
> 面板正确是因为从PDF获取的，抓取错误是因为利用PDF获取的文献信息去知网搜索错误搜索成了其它文献，可以长按某个文献，编辑它仅剩下一个作者+标题的形式成功率比较高。总之知网是块硬骨头，很难适配。

sad，大佬可以考虑恢复知网的抓取功能吗或者增加个选项让大家自己决定是否开启？之前虽然有可能会有一些错误，但准确率还是要比单纯从pdf识别的效果要好得多的。中文环境很无奈。

**Comment by MuiseDestiny** [comment]
> > 中文原本支持从知网抓的，但是指望本身参考文献信息不全，所以后来我去除了。知网文献（或者说大多数中文PDF）是没有API获取参考文献功能的。
> > 抓取错误可以把这个PDF发给我。
> > 面板正确是因为从PDF获取的，抓取错误是因为利用PDF获取的文献信息去知网搜索错误搜索成了其它文献，可以长按某个文献，编辑它仅剩下一个作者+标题的形式成功率比较高。总之知网是块硬骨头，很难适配。
> 
> sad，大佬可以考虑恢复知网的抓取功能吗或者增加个选项让大家自己决定是否开启？之前虽然有可能会有一些错误，但准确率还是要比单纯从pdf识别的效果要好得多的。中文环境很无奈。

好的

**Comment by MuiseDestiny** [comment]
> sad，大佬可以考虑恢复知网的抓取功能吗或者增加个选项让大家自己决定是否开启？之前虽然有可能会有一些错误，但准确率还是要比单纯从pdf识别的效果要好得多的。中文环境很无奈。

已支持。先关了问题了，再有问题，重新开新的issue
