### ISSUE TITLE
参考文献中间被图标阻断的怎么设置获取？

### ISSUE THREAD

**Issue by Rsweater** [MuiseDestiny/zotero-reference#65]
有阻断的好像下面的获取不了？
![2023-02-24 10 52 14](https://user-images.githubusercontent.com/49091147/221080656-85821ba8-197a-4e21-aec1-e0bbb3572423.png)

**Comment by MuiseDestiny** [comment]
这可能要借助API了。再点一下刷新。

**Comment by Rsweater** [comment]
> 这可能要借助API了。再点一下刷新。

好  感谢答疑，辛苦了/抱拳/抱拳
