### ISSUE TITLE
如何删除某条解析错误的参考文献

### ISSUE THREAD

**Issue by zyx335588** [MuiseDestiny/zotero-reference#66]
在解析完PDF后有一条解析错误产生的多余的一条文献，请问如何才能删除这条错误的信息呢，谢谢？

目前我通过长按条目，可以将条目内的信息删除，但是好像这一条文献仍然一直存在，只是显示空白。（我勾选了保存解析条目）

**Comment by MuiseDestiny** [comment]
> 在解析完PDF后有一条解析错误产生的多余的一条文献，请问如何才能删除这条错误的信息呢，谢谢？
> 
> 目前我通过长按条目，可以将条目内的信息删除，但是好像这一条文献仍然一直存在，只是显示空白。（我勾选了保存解析条目）

好像不支持删除整个文献，可以发下PDF我优化下，避免同类型PDF再出现此类问题。

**Comment by zyx335588** [comment]
> > 在解析完PDF后有一条解析错误产生的多余的一条文献，请问如何才能删除这条错误的信息呢，谢谢？
> > 目前我通过长按条目，可以将条目内的信息删除，但是好像这一条文献仍然一直存在，只是显示空白。（我勾选了保存解析条目）
> 
> 好像不支持删除整个文献，可以发下PDF我优化下，避免同类型PDF再出现此类问题。

[禾谷镰刀菌STRIPAK复...有性生殖和致病性的机制研究_吴思琪.pdf](https://github.com/MuiseDestiny/zotero-reference/files/10820465/STRIPAK._.pdf)
其实是因为我没有更改默认设置，这篇论文解析出了一篇错文的文献，我在尝试将它删除的时候，发现无法删除。
而且好像我在更改了解析页数后，刷新也并不能重新解析PDF，而是直接从本地文件读取了。感觉这个地方可以优化一下。
刚刚尝试将文献重新添加了一遍之后是可以正常解析的。
这种解析页数比较多的，如果一直保持这个解析页数，对有些电脑花费时间还是比较长的，所以不知道能不能实现[issue67](https://github.com/MuiseDestiny/zotero-reference/issues/67#issue-1597846536)的那种设置。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/221088261-4014b852-2b60-4dcf-8991-ac2922fa04ee.png)

10页是可以的

**Comment by MuiseDestiny** [comment]
建议很好，可以实现。
