### ISSUE TITLE
是否可以在侧边栏添加一个解析页码的输入框？

### ISSUE THREAD

**Issue by zyx335588** [MuiseDestiny/zotero-reference#67]
不知道能否向PDF-translate插件那样在侧边栏添加一个简单的解析页码的输入框，大家可以通过在这里输入要解析的页码来更方便的准确确定解析PDF的页码。因为有些学位论文以及部分英文文献在参考文献后面还有一些的附录等信息，页码不固定。每次都去设置页面有些繁琐，如果能在侧边栏直接调整就更好了。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.3.6 更新，尝试ctrl+长按刷新键

**Comment by zyx335588** [comment]
可以的。
有点小建议就是这种ctrl+长按刷新键的方式，尽管操作简便，可以保持界面的简洁；但对增加普通用户确增加了学习难度，需要用户去记住这个操作。这个插件加上style插件，各种点击、ctrl+点击、长按、右键点击等鼠标操作太多、太复杂了，作为一个文献工具一般用户时不会去记这些的，这也就导致很多插件的功能可能很多人并不能真正用上。从一般用户（尤其是不怎么玩游戏的）角度来说，大家更喜欢的直观的界面、按钮、鼠标提示，这也就是为什么有些插件搞一堆按钮，一长串的菜单，其实并不美观，但是仍然大量人使用，甚至愿意付费、找破解版。建议作者可以增加一些界面操作互动以及鼠标提示，这样可能更有利于用插件功能的发挥及用户的推广。当然也可能存在技术问题，仅仅是一些个人想法。

**Comment by MuiseDestiny** [comment]
很中肯的建议。这件事很值得讨论。确实是这样的，单这一个功能来说，滚动到需要解析的页面，比输入预读取页码更方便快捷。不可否认，style和ref插件都有很多长按的操作，其实手机上也有很多这种交互。ctrl点击确实需要记忆这个功能(但是特定功能就是给特别的人用的，比如点击xx条参考文献文字就会复制所有参考文献，可能大多数人都不知道，但当时提这个建议的人知道了，这次这个ctrl点击，你知道了就足够了，就算是写它有点用处)，我不想加太多按钮界面，可能加了用的人多了，但是到最后我自己都不喜欢了。就不想继续开发了。但是你讲的提示是可以的，比如style的设置界面，每个列的设置，那些字段或许只有我知道怎么用，还用个英文，这么惜字如金的(其实是懒)。

**Comment by zyx335588** [comment]
是的，自己喜欢的就是最好的。这可能就是做产品和自由开发者在理念上的不同之处之一。当然能做到苹果那样能够驯用户是最的了，是当然也是少数。
