### ISSUE TITLE
希望恢复从知网获取参考文献的功能

### ISSUE THREAD

**Issue by zhbery** [MuiseDestiny/zotero-reference#68]
之前的版本是支持从知网获取参考文献功能的，现在中文文献只支持从pdf读取，对于许多期刊的排版来说效果并不是特别理想。虽然知网直接获取可能存在漏文献之类的问题，但也比直接读取不同期刊迷惑排版格式要好许多。希望大佬能恢复这个功能或者增加一个开关的选项。

**Comment by happyfatbro** [comment]
支持！

**Comment by zhbery** [comment]
另外补充一点，好多从pdf直接提取出来参考文献信息中会出现大量的空格，导致查询时很难准确搜到对应的文献，还需要自己手动删空格，如果能从知网的数据库中获取的话就可以规避这个问题。给大佬端茶~

**Comment by MuiseDestiny** [comment]
已支持
