### ISSUE TITLE
英文期刊参考文献抓取不完整

### ISSUE THREAD

**Issue by MrGongqi** [MuiseDestiny/zotero-reference#69]
我下载的很多英文文章的参考文献抓取很不完整。明明有26篇参考文献，结果只抓取了2篇
![image](https://user-images.githubusercontent.com/49467246/222639833-d4f6db4c-5bbe-454e-8ce8-97a8875f00d8.png)
![image](https://user-images.githubusercontent.com/49467246/222639885-865fa2eb-4ad4-42ed-a58f-6a16b2c43f7a.png)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-reference/issues/6
