### ISSUE TITLE
中文支持的不是很好

### ISSUE THREAD

**Issue by niao004** [MuiseDestiny/zotero-reference#7]
0.04的中文抓取的就很好，但是英文的顺序不是很对；0.06英文的很好，顺序也基础上没问题。真希望博主能看看。

**Comment by MuiseDestiny** [comment]
可以把出错的发几个给我，我优化优化

**Comment by niao004** [comment]
我倒回了0.04，然后刚升级上来。比如“卵圆孔未闭相关卒中预防中国专家指南”，这个就一直抓不出来，0.04可以。然后我试了其他的中文，也有可以出来的。其实也挺好了。肥肠感谢。

**Comment by niao004** [comment]
[卵圆孔未闭相关卒中预防中国专家指南.pdf](https://github.com/MuiseDestiny/zotero-reference/files/10251793/default.pdf)
这个0.04可以，但是新的不行，我倒回去，然后刚升级回来了。其他中文也有可以抓到的。挺好的了。还有的参考文献不是最后的位置，是在中间好像也出不来。

**Comment by niao004** [comment]
[卵圆孔未闭相关卒中预防中国专家指南.pdf](https://github.com/MuiseDestiny/zotero-reference/files/10251793/default.pdf)
这个0.04可以，但是新的不行，我倒回去，然后刚升级回来了。其他中文也有可以抓到的。挺好的了。还有的参考文献不是最后的位置，是在中间好像也出不来。

**Comment by niao004** [comment]
肥肠感谢您的付出

**Comment by niao004** [comment]
肥肠感谢您的付出

**Comment by MuiseDestiny** [comment]
针对这篇来说，它明显是扫描生成的文字，确实无法解析，归为老旧pdf。看来要提供一个交互强制api获取

**Comment by niao004** [comment]
这样。不过出版时间还是挺新的，那这样的可能还不少。

> 针对这篇来说，它明显是扫描生成的文字，确实无法解析，归为老旧pdf。看来要提供一个交互强制api获取

**Comment by niao004** [comment]
这样。不过出版时间还是挺新的，那这样的可能还不少。

> 针对这篇来说，它明显是扫描生成的文字，确实无法解析，归为老旧pdf。看来要提供一个交互强制api获取

**Comment by niao004** [comment]
这样。不过出版时间还是挺新的，那这样的可能还不少。而且0.04可以。

> 针对这篇来说，它明显是扫描生成的文字，确实无法解析，归为老旧pdf。看来要提供一个交互强制api获取
