### ISSUE TITLE
参考文献解析有误，将一篇文献拆分成了多部分

### ISSUE THREAD

**Issue by dariushu3** [MuiseDestiny/zotero-reference#70]
> 
[基于人工智能的木材缺陷检测研究进展_刘强.pdf](https://github.com/MuiseDestiny/zotero-reference/files/10879238/_.pdf)
原文仅有47篇参考文献：
![image](https://user-images.githubusercontent.com/108558874/222658134-ff417faf-a446-4251-a76e-377e6afb4948.png)

**Comment by MuiseDestiny** [comment]
这个PDF不规范，具体就是

下面是正常顺序
![image](https://user-images.githubusercontent.com/51939531/222659978-f46331c7-0f64-46db-ad51-ef6950b3b8e5.png)

而这篇：
![image](https://user-images.githubusercontent.com/51939531/222659999-e3c06ea3-d064-46c1-b518-62d2de7f4b38.png)

可以试着复制【1】以及后面的内容，发现复制不上。
![image](https://user-images.githubusercontent.com/51939531/222660051-b4eba58e-aff2-4c2e-8a0c-d3d70caa4721.png)

**Comment by dariushu3** [comment]
十分感谢
