### ISSUE TITLE
关于能否强调显示本地已经存在的文献

### ISSUE THREAD

**Issue by TooVooT** [MuiseDestiny/zotero-reference#72]
能否将所有解析的参考文献与本地的进行一次匹配，本地已有的突出显式，否则还要一条一条看一下是否已经存在。
这样就防止二次添加重复的参考文献。

**Comment by MuiseDestiny** [comment]
可以

**Comment by MuiseDestiny** [comment]
类似问题，都需要搜索本地的：

https://github.com/MuiseDestiny/zotero-reference/issues/16

https://github.com/MuiseDestiny/zotero-reference/issues/46#issuecomment-1453101448

> 这样就防止二次添加重复的参考文献。

添加关联时候会搜索本地，如果本地有就不会重复创建条目，所以不会重复添加参考文献。

现在有DOI，arXiv容易查找，对于没有这些标识的，只有标题作者的可能做出来效果比较差。

![image](https://user-images.githubusercontent.com/51939531/222719884-bc93e205-c24b-476c-8586-4c3844b97f29.png)

**Comment by TooVooT** [comment]
关联文献中会区分本地与非本地文献，参考文献中建议也同样的区分逻辑。
![image](https://user-images.githubusercontent.com/44727734/222721922-03ea83e3-48db-43fb-bf30-daf04da3bb27.png)

**Comment by MuiseDestiny** [comment]
这个界面好做的，怎么搜索比较难。

**Comment by MuiseDestiny** [comment]
关联文献是接口返回的数据有明确的doi（一定有）所以才可以做。参考文献如果做，就要做到一个不漏。现在在思考怎么不露掉，有什么办法吗，

比如下面一条
```
—— , —— , T. Lapyonok, A. Sinyk, M. I. Mishchenko, P. Yang, and  I.  Slutsker,  2002b:  Non-spherical  aerosol  retrieval method  employing  light  scattering  by  spheroids. Geophys. Res. Lett., 29, 1415.
```

如何去搜索（已知插件不具备AI能力区分标题和作者）

**Comment by TooVooT** [comment]
这个Zotero本地标志不是已经显示本地存在了吗？
![image](https://user-images.githubusercontent.com/44727734/222723657-4d462809-e3a5-42d3-8970-0cce64a7a9a3.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/222723747-f2ebb8f9-e4a2-4d4b-8d30-9ccb3dde16ae.png)

对的，根据DOI搜索的。但是不是所有文献都有DOI。

**Comment by MuiseDestiny** [comment]
因为它不是100%匹配所以做到了这里，如果做到像关联文献一样有明暗对比，就做到100%正确。不然很有误导性，不如不做。

**Comment by MuiseDestiny** [comment]
其实这不是一个简单的功能。最核心的问题就是如何从一段文字中匹配出标题，作者。

**Comment by TooVooT** [comment]
感觉没有100%的办法，标题或作者查询，都是不能保证完全匹配

**Comment by TooVooT** [comment]
这里的双引号不是已经区分了标题了
`A.  Khanzadeh  and  M.  Pourgholi,  “Fixed-time  leader–follower  consensus  tracking  of  second-order  multi-agent  systems  with  bounded  input uncertainties  using  nonsingular  terminal  sliding  mode  technique,” IET Control Theory Appl. , vol. 12, no. 5, pp. 679–686, May 2018.`

**Comment by MuiseDestiny** [comment]
> 这里的双引号不是已经区分了标题了 `A. Khanzadeh and M. Pourgholi, “Fixed-time leader–follower consensus tracking of second-order multi-agent systems with bounded input uncertainties using nonsingular terminal sliding mode technique,” IET Control Theory Appl. , vol. 12, no. 5, pp. 679–686, May 2018.`

引文样式有很多，“”标出标题的是一部分。

**Comment by MuiseDestiny** [comment]
> “Fixed-time  leader–follower  consensus  tracking  of  second-order  multi-agent  systems  with  bounded  input uncertainties  using  nonsingular  terminal  sliding  mode  technique,”

比如你举得例子，这里面最后一个字符是逗号，可能本地存在的文献并没有逗号。这样就会匹配失败。标题中的`-`如果是中文的，而本地是英文的也会搜索匹配失败。

**Comment by MuiseDestiny** [comment]
总之这不是一个简单的功能，细节有很多，有时间做。

**Comment by TooVooT** [comment]
确实，参考文献格式太多，处理起来有点复杂

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/222868217-4f4ac200-e304-48c9-938b-687819b9927e.png)

试了下，会明显卡顿几秒能接受吗。

**Comment by TooVooT** [comment]
可以啊，只匹配一次几秒的时间完全可以接受

**Comment by MuiseDestiny** [comment]
代码是匹配了DOI，URL，标题，匹配不上会进行粗匹配，只匹配英文中文，剔除所有标点符号。
应该能做到正确率99%
```ts
let item: Zotero.Item | undefined = (
  await this.searchItem("title", "contains", info.title!) ||
  await this.searchItem("DOI", "is", info.identifiers.DOI!) ||
  await this.searchItem("url", "contains", info.identifiers.arXiv!)
)
if (!item) {
  // 进行粗暴搜索，可能时间缓慢
  const items = await Zotero.Items.getAll(1)
  item = items.filter(i => i.isRegularItem()).find((item: Zotero.Item) => {
    try {
      let getPureText = (s: string) => s.toLowerCase().match(/[a-z\u4e00-\u9fa5]+/g)?.join("")!
      const title = getPureText(item.getField("title") as string)
      const searchTitle = getPureText(info.title as string)
      if (title?.indexOf(searchTitle) != -1 || searchTitle?.indexOf(title) != -1) {
        console.log(item.getField("title"), info.title)
        return item
      }
    } catch (e) {
      console.log("error in searchLibraryItem", e)
    }
  })
}
```
