### ISSUE TITLE
功能建议：知网参考文献抓取

### ISSUE THREAD

**Issue by ZHOU1218** [MuiseDestiny/zotero-reference#73]
首先，感谢作者提供这样一个有用的功能！
其次，建议还是开启知网的api，通过api抓取参考文献，毕竟中文文献的pdf识别实在惨不忍睹。
关于知网api参考文献不足的情况，不知道可否进入全文阅读模式抓取参考文献（在有权限的情况下），那里面是全的。
https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2023&filename=NJSJ202206009&v=
以这篇为例，实际上有34篇参考文献，但详情页只展示了11篇，但如果进入全文阅读页，能看到全部的34篇参考文献。
或者能与“知网研学”软件做集成？那里面和全文阅读模式也差不多。
有这么一个初步的想法，就是不知道实施起来是否比较困难。
辛苦开发者了~

**Comment by MuiseDestiny** [comment]
已支持

**Comment by ZHOU1218** [comment]
您好，您的邮件我已收到，感谢您的来信，我将尽快处理。
                                                   周子涵

**Comment by MuiseDestiny** [comment]
泄露信息给你删除了

**Comment by ZHOU1218** [comment]
感谢大佬，厉害了大佬👍🏻



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月4日(周六) 晚上9:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MuiseDestiny/zotero-reference] 功能建议：知网参考文献抓取 (Issue #73)




 
已支持
