### ISSUE TITLE
多种来源的参考文献信息的显示顺序

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-reference#74]
目前好像悬停参考文献显示的信息有好几个来源，不知道默认显示的是哪个来源，能不能根据获取到的字段的数量来优先排序显示呢？
比如刷新参考文献后，优先显示的是最后一个信息来源
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/68216639/222936476-c056b5cc-1c89-4968-b5b7-6d164cb202f4.png">
但是最全的则是第二个信息来源：
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/68216639/222936482-7e71f2af-a107-4a82-8df0-3f674368f8f6.png">

**Comment by MuiseDestiny** [comment]
前面几个小红点，可以选择。比如分别是1-2-3

他有加载时间，等三个都加载完，你可以选择3。

此时你再浏览别的，只要3加载出来他就会自动帮你选择。加载不出来就会显示默认的1。

**Comment by MuiseDestiny** [comment]
第二个一般有摘要，但是第三个搜索结果是最准的。这也是安排多来源原因。总之点击选项后会记忆。根据标题搜索和根据doi搜索是独立记忆的选项。

**Comment by 17816712353** [comment]
> 第二个一般有摘要，但是第三个搜索结果是最准的。这也是安排多来源原因。总之点击选项后会记忆。根据标题搜索和根据doi搜索是独立记忆的选项。

确实有记忆的，👍👍，不过参考文献层次不齐，经常这个文献有的来源，那个文献没有，还是要经常手动去翻。主要是作者的功能太舒服了，让人越来越懒越来越想全自动哈哈哈哈

**Comment by MuiseDestiny** [comment]
> > 第二个一般有摘要，但是第三个搜索结果是最准的。这也是安排多来源原因。总之点击选项后会记忆。根据标题搜索和根据doi搜索是独立记忆的选项。
> 
> 确实有记忆的，👍👍，不过参考文献层次不齐，经常这个文献有的来源，那个文献没有，还是要经常手动去翻。主要是作者的功能太舒服了，让人越来越懒越来越想全自动哈哈哈哈

不能这么懒，我会很累的
