### ISSUE TITLE
参考文献显示不全

### ISSUE THREAD

**Issue by Ocean3173** [MuiseDestiny/zotero-reference#76]
您好，感谢您开发的插件为我们的学习和工作带来的便利。但我在使用过程中遇到一些小问题，因此特地向您请教。
对于一些论文，仅能识别并显示一部分参考文献。我个人的观察是：对于某一类论文，只能显示前半部分的一些文献。比如一篇论文有30个参考文献，但是在第5个换页了，插件只会显示前4个参考文献。
我不确定自己是不是个例，但上述情况确实遇到多次。下图是两个示例，第一个是仅显示了与“参考文献”四个字同页的文献；第二个则是仅显示到第79页的参考文献：
<img width="1432" alt="截屏2023-03-05 21 29 03" src="https://user-images.githubusercontent.com/127030732/222963445-6c1b483d-32a1-40dd-907d-4e39c2e8adad.png">
<img width="1431" alt="截屏2023-03-05 21 39 02" src="https://user-images.githubusercontent.com/127030732/222964020-a5bec7de-6934-4406-81de-aa06fc0e37cb.png">

**Comment by MuiseDestiny** [comment]
很奇怪，应该能全部识别的。pdf发来看看。

**Comment by Ocean3173** [comment]
以下是上图的两个文献（不好意思，我找不到在哪里传文件）：
黄冬娅 和 杜楠楠 - 2022 - 平台企业政府事务部门专门化与政企关系发展——基于国家制度环境的分析.pdf
曹 和 王 - 2019 - 从矿区政府到地方政府：中国油田地区条块关系的形成与演变.pdf

**Comment by Ocean3173** [comment]
以下也是这种例子（知网链接分别为：https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7iAEhECQAQ9aTiC5BjCgn0RsCUqXecy7D86QDM5MR7ZK6ur2kpDNKbUyEIYKUnWGLj&uniplatform=NZKPT
https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7i8oRR1PAr7RxjuAJk4dHXosKQLAJmItsyjYw728yqFMaj4qk3sfpDcCXgPUMLZlm7&uniplatform=NZKPT
<img width="1381" alt="截屏2023-03-05 22 07 18" src="https://user-images.githubusercontent.com/127030732/222965415-831a899d-df12-4f04-a052-de2788b04e46.png">
<img width="1385" alt="截屏2023-03-05 22 05 38" src="https://user-images.githubusercontent.com/127030732/222965420-a226055b-f826-4ff9-a06d-7515c80e8365.png">

**Comment by MuiseDestiny** [comment]
> 以下也是这种例子（知网链接分别为：https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7iAEhECQAQ9aTiC5BjCgn0RsCUqXecy7D86QDM5MR7ZK6ur2kpDNKbUyEIYKUnWGLj&uniplatform=NZKPT https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7i8oRR1PAr7RxjuAJk4dHXosKQLAJmItsyjYw728yqFMaj4qk3sfpDcCXgPUMLZlm7&uniplatform=NZKPT <img alt="截屏2023-03-05 22 07 18" width="1381" src="https://user-images.githubusercontent.com/127030732/222965415-831a899d-df12-4f04-a052-de2788b04e46.png"> <img alt="截屏2023-03-05 22 05 38" width="1385" src="https://user-images.githubusercontent.com/127030732/222965420-a226055b-f826-4ff9-a06d-7515c80e8365.png">

尝试从知网API获取呢

**Comment by Ocean3173** [comment]
我在首选项里改成“API”后再点刷新就会程序崩溃，尝试多次后也是这样，目前我只能用PDF。即使是PDF，如果连续点刷新也会崩溃，不知道是不是我电脑或者macOS的问题。（reference和茉莉花插件版本都是最新）

**Comment by MuiseDestiny** [comment]
> 我在首选项里改成“API”后再点刷新就会程序崩溃，尝试多次后也是这样，目前我只能用PDF。即使是PDF，如果连续点刷新也会崩溃，不知道是不是我电脑或者macOS的问题。（reference和茉莉花插件版本都是最新）

我也会卡，是因为cnki不支持它，就循环调用导致卡的。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/223003600-40b7a8ae-fad5-4d05-a537-ba0a9b1bc6b5.png)

用API，稍后更新，需要配置账号密码

**Comment by MuiseDestiny** [comment]
用知网API获取。

**Comment by Kaergo** [comment]
我想请问在哪里配置知网研学账户密码？

**Comment by MuiseDestiny** [comment]
> 我想请问在哪里配置知网研学账户密码？

看下即使发布，有一个发布讲了。

**Comment by LNZ59211** [comment]
我想请问在哪里配置知网研学账户密码？

**Comment by YUNYUNLUCKY** [comment]
> > 我想请问在哪里配置知网研学账户密码？
> 
> 看下即使发布，有一个发布讲了。

请问即使发布是什么？
