### ISSUE TITLE
【无响应BUG】今天（23.3.6）更新的0.3.8版本Zotero Reference打开文献会让Zotero无响应

### ISSUE THREAD

**Issue by jackdhch** [MuiseDestiny/zotero-reference#77]
如题，今天早上打开Zotero阅读文献发现在主界面正常，但是一点进文献Zotero就无响应。通过逐个停用插件锁定到了Zotero Reference，发现是今天更新的。
![QQ截图20230306093249](https://user-images.githubusercontent.com/38135335/223000038-7f2ce82a-5b8e-49d5-b489-d46483e5ebc7.png)

**Comment by MuiseDestiny** [comment]
已更新修复，请更新
