### ISSUE TITLE
mac上使用时资源占用率过高，导致软件卡顿

### ISSUE THREAD

**Issue by hacker-jerry** [MuiseDestiny/zotero-reference#80]
作者你好，在安装了插件之后，获取参考文献的时候速度很快。
但是悬停几次就会卡死，不知道是哪里出了bug? 看了一下系统占用率也比较高，不知道有没有可能优化一下，比如改成异步获取之类的？
<img width="593" alt="image" src="https://user-images.githubusercontent.com/57279550/223308573-db577a23-39ed-457b-81a0-c4c9aa3dce8c.png">

**Comment by MuiseDestiny** [comment]
> 作者你好，在安装了插件之后，获取参考文献的时候速度很快。 但是悬停几次就会卡死，不知道是哪里出了bug? 看了一下系统占用率也比较高，不知道有没有可能优化一下，比如改成异步获取之类的？ <img alt="image" width="593" src="https://user-images.githubusercontent.com/57279550/223308573-db577a23-39ed-457b-81a0-c4c9aa3dce8c.png">

查找本地文献导致的。关闭就可以了。首选项最后一个框0.5改成1

**Comment by MuiseDestiny** [comment]
试试0.4.0

**Comment by hacker-jerry** [comment]
> 试试0.4.0

谢谢，问题解决啦
