### ISSUE TITLE
能否将参考文献导入到指定的文件夹中呢？

### ISSUE THREAD

**Issue by Xu-Jam** [MuiseDestiny/zotero-reference#9]

**Comment by MuiseDestiny** [comment]
可以，想要什么样的交互

**Comment by Xu-Jam** [comment]
> 可以，想要什么样的交互
我看目前点击左键和右键效果是一样的，能否右键所选参考文献后出现已有文件夹，点击文件夹后将该条参考文献加入到所选文件夹中

**Comment by MuiseDestiny** [comment]
可以，但是mac好像没有右键

**Comment by MuiseDestiny** [comment]
跟点击条目`ctrl+点击`跳转网页一样，也ctrl点击吧

**Comment by Xu-Jam** [comment]
> 跟点击条目`ctrl+点击`跳转网页一样，也ctrl点击吧
ctrl＋点击的话，如果能够将参考文献导入指定文件夹的话，如何实现多选呢？加选框吗

**Comment by MuiseDestiny** [comment]
多选什么，多选文件夹吗

**Comment by Xu-Jam** [comment]
> 多选什么，多选文件夹吗

选中多条参考文献添加到指定文件夹

**Comment by MuiseDestiny** [comment]
现在不支持选中多条，这个功能在考虑加不加

**Comment by Xu-Jam** [comment]
> 现在不支持选中多条，这个功能在考虑加不加

好吧，期待您的插件能够给我们带来更高的生产力，向开发者致敬！

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/208288568-466954d6-ac46-42a1-9cfc-305fa82fd590.png)

交互比较难实现
本来想实现这样类似的弹窗，但zotero只有选择条目的弹框，没有选择文件夹的弹窗。
![image](https://user-images.githubusercontent.com/51939531/208288694-75e95829-7c7a-4fd3-be20-6932c248f18a.png)
浏览器插件是有的，但是并不是在zotero内实现，无法直接调用。
![image](https://user-images.githubusercontent.com/51939531/208288613-b2cc4811-21b2-4ed4-9b6f-97ccca12fce1.png)

最后采取了一种简单实现的方案，按ctrl点击+，会添加到下图主界面选择的文件夹。
![image](https://user-images.githubusercontent.com/51939531/208288635-567ae21c-c0a1-4ceb-8536-123b0c5790a1.png)

**Comment by Xu-Jam** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/208288568-466954d6-ac46-42a1-9cfc-305fa82fd590.png)
> 
> 交互比较难实现 本来想实现这样类似的弹窗，但zotero只有选择条目的弹框，没有选择文件夹的弹窗。 ![image](https://user-images.githubusercontent.com/51939531/208288694-75e95829-7c7a-4fd3-be20-6932c248f18a.png) 浏览器插件是有的，但是并不是在zotero内实现，无法直接调用。 ![image](https://user-images.githubusercontent.com/51939531/208288613-b2cc4811-21b2-4ed4-9b6f-97ccca12fce1.png)
> 
> 最后采取了一种简单实现的方案，按ctrl点击+，会添加到下图主界面选择的文件夹。 ![image](https://user-images.githubusercontent.com/51939531/208288635-567ae21c-c0a1-4ceb-8536-123b0c5790a1.png)

哦哦，这样也挺方便，等更新

**Comment by Xu-Jam** [comment]
> > ![image](https://user-images.githubusercontent.com/51939531/208288568-466954d6-ac46-42a1-9cfc-305fa82fd590.png)
> > 交互比较难实现 本来想实现这样类似的弹窗，但zotero只有选择条目的弹框，没有选择文件夹的弹窗。 ![image](https://user-images.githubusercontent.com/51939531/208288694-75e95829-7c7a-4fd3-be20-6932c248f18a.png) 浏览器插件是有的，但是并不是在zotero内实现，无法直接调用。 ![image](https://user-images.githubusercontent.com/51939531/208288613-b2cc4811-21b2-4ed4-9b6f-97ccca12fce1.png)
> > 最后采取了一种简单实现的方案，按ctrl点击+，会添加到下图主界面选择的文件夹。 ![image](https://user-images.githubusercontent.com/51939531/208288635-567ae21c-c0a1-4ceb-8536-123b0c5790a1.png)
> 
> 哦哦，这样也挺方便，等更新

再提个建议，是否能够实现鼠标停留在参考文献上出现悬浮框显示参考文献全部信息

**Comment by MuiseDestiny** [comment]
已经实现了的
![image](https://user-images.githubusercontent.com/51939531/208288960-b44e4a37-08aa-412f-969a-a1c2df16cef8.png)

**Comment by Xu-Jam** [comment]
> 已经实现了的 ![image](https://user-images.githubusercontent.com/51939531/208288960-b44e4a37-08aa-412f-969a-a1c2df16cef8.png)

win 11 6.0.18版本上没有。。。

**Comment by MuiseDestiny** [comment]
更新下插件，0.0.8，我也是win11  6.0.18

**Comment by zyx335588** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/208288568-466954d6-ac46-42a1-9cfc-305fa82fd590.png)
> 
> 交互比较难实现 本来想实现这样类似的弹窗，但zotero只有选择条目的弹框，没有选择文件夹的弹窗。 ![image](https://user-images.githubusercontent.com/51939531/208288694-75e95829-7c7a-4fd3-be20-6932c248f18a.png) 浏览器插件是有的，但是并不是在zotero内实现，无法直接调用。 ![image](https://user-images.githubusercontent.com/51939531/208288613-b2cc4811-21b2-4ed4-9b6f-97ccca12fce1.png)
> 
> 最后采取了一种简单实现的方案，按ctrl点击+，会添加到下图主界面选择的文件夹。 ![image](https://user-images.githubusercontent.com/51939531/208288635-567ae21c-c0a1-4ceb-8536-123b0c5790a1.png)

是不是可以考虑，在刷新按钮旁边添加一个列表框，让大家选择可以添加到哪个文件夹，或者类似主界面上添加到分类那样的层级选择菜单。

**Comment by MuiseDestiny** [comment]
> 在刷新按钮旁边添加一个列表框，让大

感觉空间太小了，不太好布局，在右侧很尴尬，施展空间很小。
以后可以考虑这么做，现在先把核心功能做好。
