### ISSUE TITLE
首选项里面看不到插件的设置项

### ISSUE THREAD

**Issue by tcmtom** [MuiseDestiny/zotero-reference#90]
![image](https://user-images.githubusercontent.com/94541098/224926025-843f7607-efc7-4912-84b0-2203883ca021.png)
![image](https://user-images.githubusercontent.com/94541098/224926158-b9d16541-9abf-4d2e-aa3a-bd5ef0ab8d23.png)
![image](https://user-images.githubusercontent.com/94541098/224926452-7566da9a-2517-4ffd-85bb-6868bf83a427.png)

明明已经打开并且可以正常使用，但是首选项里面看不到设置项
zotero-pdf-translate插件也存在这个问题https://github.com/windingwind/zotero-pdf-translate/issues/393

**Comment by MuiseDestiny** [comment]
都出现这种情况的话，建议更新Zotero版本

**Comment by tcmtom** [comment]
> 都出现这种情况的话，建议更新Zotero版本

版本是6.0.23

**Comment by MuiseDestiny** [comment]
更新beta或者发错误日志

**Comment by tcmtom** [comment]
> 更新beta或者发错误日志

发日志id您能看到吗：D1793643719

**Comment by tcmtom** [comment]
[Debug Output.zip](https://github.com/MuiseDestiny/zotero-reference/files/10966542/Debug.Output.zip)

**Comment by tcmtom** [comment]
beta版也是一样的

**Comment by MuiseDestiny** [comment]
xml解析失败导致的无法加载。但是好像目前只有你反馈了这个问题，所以问题不在两个插件写的xml上。

**Comment by MuiseDestiny** [comment]
我建议切换到英文版试试。或者看看俩是不是都最新，在github重新下载安装

**Comment by tcmtom** [comment]
两个插件都是最新版，切换到英文版也一样
![图片](https://user-images.githubusercontent.com/94541098/224958594-1d2cc57c-b040-4ede-80e9-125d20ec8bed.png)

**Comment by tcmtom** [comment]
管理员模式启动zotero也不行，重装插件也一样

**Comment by MuiseDestiny** [comment]
没事的，这样也可以设置，以reference为例
![image](https://user-images.githubusercontent.com/51939531/224975084-8c1b798a-bbda-42d2-82bd-17b098cb35ad.png)

**Comment by tcmtom** [comment]
> 

![image](https://user-images.githubusercontent.com/94541098/224988439-6d595b4e-930d-422f-bfd1-2e41d969df21.png)

这个怎么设置呀
---
把其他的插件全部都禁掉这两个的设置项倒是出来了

**Comment by MuiseDestiny** [comment]
> 把其他的插件全部都禁掉这两个的设置项倒是出来了

可以测试下具体是谁影响了他俩

**Comment by MuiseDestiny** [comment]
直接点击编辑就可以

**Comment by tcmtom** [comment]
> > 把其他的插件全部都禁掉这两个的设置项倒是出来了
> 
> 可以测试下具体是谁影响了他俩

经过逐个开启插件之后发现是[pubpeer_zotero_plugin](https://github.com/PubPeerFoundation/pubpeer_zotero_plugin) 这个插件的原因，把这个插件禁掉就好了

**Comment by MuiseDestiny** [comment]
好的，这样方便同样问题用户快速排查

**Comment by tcmtom** [comment]
这个问题好像一时半会解决不了，建议您把这个冲突写到redme里面，那样能看到的人更多。

**Comment by tcmtom** [comment]
https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/issues/44#issuecomment-1475351566
pubpeer0.0.16版本已经解决该问题。
