### ISSUE TITLE
用插件 zotero 会变得很卡，建议优化性能

### ISSUE THREAD

**Issue by heimi98** [MuiseDestiny/zotero-reference#91]
用该插件 zotero 会变得很卡，建议优化性能。

**Comment by MuiseDestiny** [comment]
请关闭自动搜索本地，首选项最后一个空设置为1

**Comment by heimi98** [comment]
> 请关闭自动搜索本地，首选项最后一个空设置为1

透明度？
![image](https://user-images.githubusercontent.com/56879067/225267747-14635c0f-b16a-4780-900c-2747bba7ad21.png)

**Comment by MuiseDestiny** [comment]
> > 请关闭自动搜索本地，首选项最后一个空设置为1
> 
> 透明度？ ![image](https://user-images.githubusercontent.com/56879067/225267747-14635c0f-b16a-4780-900c-2747bba7ad21.png)

对的

**Comment by MuiseDestiny** [comment]
设置1不会搜索，就不会卡
