### ISSUE TITLE
“分栏快速跳转”功能无法使用

### ISSUE THREAD

**Issue by DrAntonioWong** [MuiseDestiny/zotero-reference#93]
[点击自带跳转功能的参考文献或者图片、表格，无法像之前一样实现自动分屏展示。而是主屏自动跳转。DOI：10.1161/JAHA.122.027619]

**Comment by MuiseDestiny** [comment]
所有都没发跳转吗。目前已知有一些pdf无法跳转。

**Comment by xxmywxy** [comment]
同样的问题，之前可以分屏的文件现在也不行了。感觉是昨天zotero style更新了之后就不行了。

**Comment by DrAntonioWong** [comment]
> 所有都没发跳转吗。目前已知有一些pdf无法跳转。

之前可以自动分屏的软件都无法自动分屏了。

**Comment by MuiseDestiny** [comment]
> > 所有都没发跳转吗。目前已知有一些pdf无法跳转。
> 
> 之前可以自动分屏的软件都无法自动分屏了。

没有误触关闭这个功能吧

**Comment by DrAntonioWong** [comment]
> > > 所有都没发跳转吗。目前已知有一些pdf无法跳转。
> > 
> > 
> > 之前可以自动分屏的软件都无法自动分屏了。
> 
> 没有误触关闭这个功能吧

没有，特意检查过。

**Comment by xjin15** [comment]
我没安装zotero-style 也无法正常跳转了，我只安装了zotero-citation，茉莉花，zoteroPDFtranslate等
![GIF 2023-03-19 16-10-45](https://user-images.githubusercontent.com/78125804/226162254-a2b62cad-8e5f-4a68-86e4-a220d90bc957.gif)

**Comment by MuiseDestiny** [comment]
我试试

**Comment by MuiseDestiny** [comment]
> [点击自带跳转功能的参考文献或者图片、表格，无法像之前一样实现自动分屏展示。而是主屏自动跳转。DOI：10.1161/JAHA.122.027619]

退回到上一个版本可以跳转吗。最近几个版本我没有改动跳转这一块代码。很奇怪

**Comment by DrAntonioWong** [comment]
感谢，在更新后问题已成功解决。

**Comment by MuiseDestiny** [comment]
好的

**Comment by Adelaide-emporor** [comment]
更新了插件还是zotero
