### ISSUE TITLE
使用tranlate翻译的时切换到翻译tab，没有切到参考文献tab，概率性弹出参考文献的弹窗

### ISSUE THREAD

**Issue by Lyn6969** [MuiseDestiny/zotero-reference#95]
大佬您好，又是我。。。我要反馈一下reference的一个bug。

当我使用translate在pdf中进行划句翻译时，有概率会弹出参考文献的弹窗，如下图所示。
这个我也不确定是怎么触发的，虽然是概率性的，但是频率相当高，当右边的tab不是参考文献栏的时候也会弹窗吗？是不是又是什么插件之间的冲突？谢谢大佬，辛苦您了

![image](https://user-images.githubusercontent.com/42564665/226370819-814b661e-8f39-44bc-a849-3e375adc9c71.png)

![image](https://user-images.githubusercontent.com/42564665/226370105-e05a7c08-b706-45eb-a380-65d678276c67.png)

**Comment by MuiseDestiny** [comment]
这是新功能但是没做好，下个版本就砍了它

**Comment by Lyn6969** [comment]
好吧🤣😂
