### ISSUE TITLE
推荐文献功能和可关联文献功能 是 取消/消失了？

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-reference#96]
reference最近两个版本是把`推荐文献功能`和`可关联文献功能` 取消了？还是这个功能有BUG了？

另外，能够实现希望能够实现方案一：在主面板显示 `推荐文献功能`和`可关联文献功能` 

![](https://user-images.githubusercontent.com/104330036/224973637-fdd82f31-0665-4483-993f-163598178f54.png)

![](https://user-images.githubusercontent.com/104330036/224304980-6a5bf999-0974-4df5-a160-6af64b42ab60.png)

**Comment by 1067237855** [comment]
超好用的功能，期待早日恢复
> 原API限制了，需要token，所以失效

**Comment by MuiseDestiny** [comment]
> 超好用的功能，期待早日恢复

恢复了，用semanticscholar了，它提供的更多。设置了最大20个

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/226560354-e1eb90d0-10e5-4be5-a1fb-fbbe70919caf.png)

**Comment by 1067237855** [comment]
> 希望能够实现方案一：在主面板显示 `推荐文献功能`和`可关联文献功能`

**Comment by MuiseDestiny** [comment]
> > 希望能够实现方案一：在主面板显示 `推荐文献功能`和`可关联文献功能`

考虑中。

**Comment by 1067237855** [comment]
右侧添加一个刷新按钮，PDF阅读器内部也加上，如果可以的话`参考文献`的保存功能也可以移植到`关联文献`中。尽量减少访问频次。
![image](https://user-images.githubusercontent.com/104330036/227460466-b6fe57de-ee69-454f-adda-873deeff6fb4.png)

> 因为这样会频繁触发API请求，怕太频繁API采取限制，上一个api已经没了

**Comment by MuiseDestiny** [comment]
> 因为这样会频繁触发API请求，怕太频繁API采取限制，上一个api已经没了

有时间做

**Comment by MuiseDestiny** [comment]
都会实现的

**Comment by 1067237855** [comment]
> 都会实现的

牛逼( ఠൠఠ )ﾉ🐂
[0.5.3: 支持解析断开参考文献；PDF链接优化](https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.5.3)
c 除了牛逼我无话可说

![image](https://user-images.githubusercontent.com/104330036/227531944-10862295-bba0-43bb-8c4b-5de9b0746918.png)
