### ISSUE TITLE
更新最新版后，参考文献栏不见了

### ISSUE THREAD

**Issue by 17816712353** [MuiseDestiny/zotero-reference#97]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/68216639/226772862-c0d4b3af-5444-477a-a81e-067c600e4588.png">

**Comment by MuiseDestiny** [comment]
重新下载最新版解决。老问题了。

**Comment by 17816712353** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/68216639/226780885-2a16bf57-9c52-4af3-aad8-6cf850091b12.png">
这个按钮和style里的文献网络是啥关系啊？可以取消这个吗？

**Comment by MuiseDestiny** [comment]
> <img alt="image" width="484" src="https://user-images.githubusercontent.com/68216639/226780885-2a16bf57-9c52-4af3-aad8-6cf850091b12.png">
> 
> 这个按钮和style里的文献网络是啥关系啊？可以取消这个吗？

弄错了，重新上传了，重新下载安装。
