### ISSUE TITLE
[Bug]同时打开多个PDF文件时，仅在第一个文件页面出现参考文献

### ISSUE THREAD

**Issue by dcgggg** [MuiseDestiny/zotero-reference#98]
开发者你好：
     该情况已经出现在[zotero-pdf-translate](https://github.com/windingwind/zotero-pdf-translate)插件中，详情可见：https://github.com/windingwind/zotero-pdf-translate/issues/401。
     在更新最新版本[zotero-reference]后，我发现出现了和上述问题同样的情况。
![图片](https://user-images.githubusercontent.com/87225817/226818855-0adcfdba-6e98-4059-aeb3-3593b228f0e0.png)
![图片](https://user-images.githubusercontent.com/87225817/226818893-d0128977-da3e-4636-b2b1-82b5d0da4aa0.png)

通过禁用其他插件，我发现Night to zotero,zotero-style,Chartero 插件和这个bug有密切关系，禁用Chartero 插件后bug消失。
希望收到回复谢谢！

**Comment by MuiseDestiny** [comment]
安装我发布的night插件解决night的问题

**Comment by dcgggg** [comment]
收到，感谢您的回复

**Comment by RinkoooZ** [comment]
hello，同样存在多个参考文献的框框问题，安装了好多插件，不知道哪个插件不兼容了，应该怎么更好解决
![image](https://user-images.githubusercontent.com/103426184/229411871-15a4b364-848b-4d06-9157-c258172d26da.png)

**Comment by MuiseDestiny** [comment]
> hello，同样存在多个参考文献的框框问题，安装了好多插件，不知道哪个插件不兼容了，应该怎么更好解决 ![image](https://user-images.githubusercontent.com/103426184/229411871-15a4b364-848b-4d06-9157-c258172d26da.png)

用我发布的night插件

**Comment by RinkoooZ** [comment]
> 

可是 我没有用night插件

**Comment by MuiseDestiny** [comment]
> > 
> 
> 可是 我没有用night插件

禁用其他的试试，因为你截图翻译插件也双个了，说明是受到其他插件影响。

**Comment by mingo99** [comment]
用博主你的night插件也会出现这个问题，禁用night插件就好了

**Comment by MuiseDestiny** [comment]
请更新
