### ISSUE TITLE
tip浮窗的小bug

### ISSUE THREAD

**Issue by alittleking** [MuiseDestiny/zotero-reference#99]
作者：你好！

首先十分感谢作者提供的插件，非常好用！

然而，目前我在使用中发现了一个浮窗的小bug，仅靠现有的设置似乎没有办法解决。

在 view -> layout -> stacked view 下，浮窗呈长条形，这似乎是一个bug，在standard view下并不会出现。

![c477d40bec1c9c8b0e1bc09231cb569](https://user-images.githubusercontent.com/32083977/227122215-bb8b7e2e-ad21-4b25-a89b-3706514f1095.png)

**Comment by MuiseDestiny** [comment]
很久之前有用户提出要适配这种显示模式，但是综合考虑了一下，不好实现，而且那位用户也不经常使用这种视图。所以就没做。你经常使用这种视图吗。

**Comment by alittleking** [comment]
因为宽屏阅读的便利性，例如standard view下，reference经常都无法显示完整，所以大部分是否都采用这种视图
(。_。)

**Comment by alittleking** [comment]
因为宽屏阅读的便利性，例如standard view下，reference经常都无法显示完整，所以大部分时间都采用这种视图
(。_。)

**Comment by MuiseDestiny** [comment]
> 因为宽屏阅读的便利性，例如standard view下，reference经常都无法显示完整，所以大部分时间都采用这种视图 (。_。)

好的，计划适配

**Comment by alittleking** [comment]
十分感谢作者的付出，每一个项目都是心血和无私的付出，后续会考虑开通捐赠渠道吗，衷心希望项目能持续更新下去。

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/227142819-e1c390e0-3244-4394-9ca8-30d5ee8e7a8e.png)

我试了下，你只能在红色区域外进行选择

![image](https://user-images.githubusercontent.com/51939531/227142946-c1562689-d35f-409c-a4e3-500a81b89e20.png)

**Comment by alittleking** [comment]
这似乎已经足够了hhh

**Comment by MuiseDestiny** [comment]
> 十分感谢作者的付出，每一个项目都是心血和无私的付出，后续会考虑开通捐赠渠道吗，衷心希望项目能持续更新下去。

readme加了，https://github.com/MuiseDestiny/zotero-reference/releases/tag/0.5.2
堆叠更新后支持。
